package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.constants.Constants;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class bottom extends CustomComponent implements Constants {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;

	public bottom() {
		buildMainLayout();
		
		setCompositionRoot(mainLayout);
		mainLayout.setWidth(Constants.WIDTH_MAX, Sizeable.UNITS_PIXELS) ;
		mainLayout.setStyleName("bottomPanel") ;

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);		
		mainLayout.setWidth("100%");
		mainLayout.setHeight("60px");
		mainLayout.setMargin(false);
		
		// top-level component properties
//		setWidth("100.0%");
//		setHeight("60px");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue(BOTTOM_LINE1);
		mainLayout.addComponent(label_2);
		mainLayout.setComponentAlignment(label_2, new Alignment(20));
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue(BOTTOM_LINE2);
		mainLayout.addComponent(label_3);
		mainLayout.setComponentAlignment(label_3, new Alignment(20));
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue(BOTTOM_LINE3);
		mainLayout.addComponent(label_1);
		mainLayout.setComponentAlignment(label_1, new Alignment(20));
		
		return mainLayout;
	}

}
