package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.QlgiangvienApplication;
import cit.group10.qlGiangvien.UserFunctions;
import cit.group10.qlGiangvien.TeacherInfo.WindowAddNewTeacher;
import cit.group10.qlGiangvien.constants.Constants;
import cit.group10.qlGiangvien.detailedInfo.researching.WindowRegistedResearching;
import cit.group10.qlGiangvien.detailedInfo.researching.WindowResearching;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;

import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class leftSide extends CustomComponent implements Constants, ItemClickListener {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	@AutoGenerated
	private Tree leftMenu;
	
	
	private int userRole =0 ;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public leftSide() {
	
		try{
			
		userRole =Integer.valueOf( QlgiangvienApplication.getInstance().getUser().toString().substring(0, 1) );
		} catch(Exception e){
			userRole =0 ;
		}
		
		System.out.println("print role in left side :"+ userRole) ;
		
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
//		setWidth(Constants.WIDTH_LEFT_MENU, Sizeable.UNITS_PIXELS);S

		switch (userRole){
		case 1 :
			for (int i=0; i< MAIN_MENU_TEXT_ADMIN[2].length; i++) leftMenu.addItem(MAIN_MENU_TEXT_ADMIN[2][i]) ;
			break;
		case 0:
			for (int i=0; i< MAIN_MENU_TEXT_USER[2].length; i++) leftMenu.addItem(MAIN_MENU_TEXT_USER[2][i]) ;
			break;
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// leftMenu
		leftMenu = new Tree();
		leftMenu.addListener(this) ;
		leftMenu.setStyleName("leftMenu");
		leftMenu.setImmediate(false);
		leftMenu.setWidth("-1px");
		leftMenu.setHeight("-1px");
		mainLayout.addComponent(leftMenu);
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setImmediate(false);
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");
		inlineDateField_1.setInvalidAllowed(false);
		mainLayout.addComponent(inlineDateField_1);
		
		return mainLayout;
	}

	@Override
	public void itemClick(ItemClickEvent event) {
		
		getWindow().showNotification("in user Action " + event.getItem().toString() +"--" +event.getItemId().toString() ) ;
		
    	Window newWindow ;
    	
    	String sub = event.getItemId().toString() ;
    	
    	if (sub.equals(MAIN_MENU_TEXT_ADMIN[2][0])) {
    		
    		newWindow = new WindowAddNewTeacher();					
			newWindow.setName(sub) ;	
			QlgiangvienApplication.getInstance().setNewWindow(newWindow) ;
    	}
    	if (sub.equals(MAIN_MENU_TEXT_ADMIN[2][1])) {
    		
    		newWindow = new WindowAddNewTeacher();					
			newWindow.setName(sub) ;	
			QlgiangvienApplication.getInstance().setNewWindow(newWindow) ;
    	}
    			
		
		
	}

}
