package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.QlgiangvienApplication;
import cit.group10.qlGiangvien.constants.Constants;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

public class leftSide extends CustomComponent implements Constants{

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	@AutoGenerated
	private Tree leftMenu;
	
	
	private int userRole =0 ;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public leftSide() {
		
		System.out.println(QlgiangvienApplication.getInstance().getUser().toString() );
		
		userRole =Integer.valueOf( QlgiangvienApplication.getInstance().getUser().toString().substring(0, 1) );
		System.out.println("print role in left side :"+ userRole) ;
		
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
//		setWidth(Constants.WIDTH_LEFT_MENU, Sizeable.UNITS_PIXELS);S

		switch (userRole){
		case 1 :
			for (int i=0; i< MAIN_MENU_TEXT_ADMIN[2].length; i++) leftMenu.addItem(MAIN_MENU_TEXT_ADMIN[2][i]) ;
			break;
		case 0:
			for (int i=0; i< MAIN_MENU_TEXT_USER[2].length; i++) leftMenu.addItem(MAIN_MENU_TEXT_USER[2][i]) ;
			break;
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// leftMenu
		leftMenu = new Tree();
		leftMenu.setStyleName("leftMenu");
		leftMenu.setImmediate(false);
		leftMenu.setWidth("-1px");
		leftMenu.setHeight("-1px");
		mainLayout.addComponent(leftMenu);
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setImmediate(false);
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");
		inlineDateField_1.setInvalidAllowed(false);
		mainLayout.addComponent(inlineDateField_1);
		
		return mainLayout;
	}

}
