package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.VerticalLayout;

public class rightContentImport extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private ListSelect listSelect_1;
	@AutoGenerated
	private Button btnImport;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentImport() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("360px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("360px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h1>Import thong tin giang vien</h1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// label_2
		label_2 = new Label();
		label_2.setCaption("Chon file ");
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("<input class=\"gwt-FileUpload\" type=\"file\" name=\"PID64_file\">");
		label_2.setContentMode(3);
		mainLayout.addComponent(label_2);
		
		// btnImport
		btnImport = new Button();
		btnImport.setCaption("Import");
		btnImport.setImmediate(true);
		btnImport.setWidth("-1px");
		btnImport.setHeight("-1px");
		mainLayout.addComponent(btnImport);
		
		// listSelect_1
		listSelect_1 = new ListSelect();
		listSelect_1.setCaption("FIle import co cac truong theo thu tu sau :");
		listSelect_1.setImmediate(false);
		listSelect_1.setWidth("560px");
		listSelect_1.setHeight("-1px");
		mainLayout.addComponent(listSelect_1);
		
		return mainLayout;
	}

}
