package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class rightContentAddInfoGV extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheetInfoGV;
	@AutoGenerated
	private VerticalLayout tabNghienCuuKH;
	@AutoGenerated
	private PopupDateField popNgayKetThuc;
	@AutoGenerated
	private PopupDateField popNgayBatDau;
	@AutoGenerated
	private TextField textLoaiCTNC;
	@AutoGenerated
	private TextField textTenCTNC;
	@AutoGenerated
	private TabSheet tabsheetHocHamHocVi;
	@AutoGenerated
	private VerticalLayout tabHocHam;
	@AutoGenerated
	private TextArea txtDienGiai;
	@AutoGenerated
	private PopupDateField popThoiGianDat;
	@AutoGenerated
	private TextField txtTenHocHam;
	@AutoGenerated
	private VerticalLayout tabHocVi;
	@AutoGenerated
	private TextField txtDiaChiTruongDT;
	@AutoGenerated
	private PopupDateField popNgayKT;
	@AutoGenerated
	private PopupDateField popNgayBD;
	@AutoGenerated
	private TextField txtTenTruongDT;
	@AutoGenerated
	private TextField txtTenHocVi;
	@AutoGenerated
	private VerticalLayout tabThongTinCongTacGV;
	@AutoGenerated
	private TextField textNoiDungKL;
	@AutoGenerated
	private TextField textKyLuat;
	@AutoGenerated
	private TextField textNoiDungKT;
	@AutoGenerated
	private TextField textKhenThuong;
	@AutoGenerated
	private ComboBox comBoMon;
	@AutoGenerated
	private PopupDateField popNgayHuong;
	@AutoGenerated
	private TextField textBacLuong;
	@AutoGenerated
	private TextField txtHeSoLuongGV;
	@AutoGenerated
	private VerticalLayout tabCoBan;
	@AutoGenerated
	private TextArea txtGhiChuGV;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtDienThoai;
	@AutoGenerated
	private TextField txtDiaChi;
	@AutoGenerated
	private ComboBox txtGioiTinh;
	@AutoGenerated
	private PopupDateField txtNgaySinh;
	@AutoGenerated
	private TextField txtHoTenGV;
	@AutoGenerated
	private TextField txtMaGV;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btnApply;
	@AutoGenerated
	private Button btnDelete;
	@AutoGenerated
	private Label label_1;

	
	public rightContentAddInfoGV() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("614px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("614px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("-1px");
		label_1.setValue("<h1>Thông tin giảng viên </h1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(6));
		
		// tabSheetInfoGV
		tabSheetInfoGV = buildTabSheetInfoGV();
		mainLayout.addComponent(tabSheetInfoGV);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// btnDelete
		btnDelete = new Button();
		btnDelete.setCaption("Delete");
		btnDelete.setImmediate(true);
		btnDelete.setWidth("-1px");
		btnDelete.setHeight("-1px");
		horizontalLayout_1.addComponent(btnDelete);
		horizontalLayout_1.setComponentAlignment(btnDelete, new Alignment(6));
		
		// btnApply
		btnApply = new Button();
		btnApply.setCaption("Apply");
		btnApply.setImmediate(true);
		btnApply.setWidth("-1px");
		btnApply.setHeight("-1px");
		horizontalLayout_1.addComponent(btnApply);
		horizontalLayout_1.setComponentAlignment(btnApply, new Alignment(6));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private TabSheet buildTabSheetInfoGV() {
		// common part: create layout
		tabSheetInfoGV = new TabSheet();
		tabSheetInfoGV.setImmediate(true);
		tabSheetInfoGV.setWidth("100.0%");
		tabSheetInfoGV.setHeight("479px");
		
		// tabCoBan
		tabCoBan = buildTabCoBan();
		tabSheetInfoGV.addTab(tabCoBan, "Thông tin cơ bản", null);
		
		// tabThongTinCongTacGV
		tabThongTinCongTacGV = buildTabThongTinCongTacGV();
		tabSheetInfoGV.addTab(tabThongTinCongTacGV, "Thông tin công tác", null);
		
		// tabsheetHocHamHocVi
		tabsheetHocHamHocVi = buildTabsheetHocHamHocVi();
		tabSheetInfoGV.addTab(tabsheetHocHamHocVi, "Hoc hàm, học vị", null);
		
		// tabNghienCuuKH
		tabNghienCuuKH = buildTabNghienCuuKH();
		tabSheetInfoGV.addTab(tabNghienCuuKH, "Nghiên cứu khoa học", null);
		
		return tabSheetInfoGV;
	}

	@AutoGenerated
	private VerticalLayout buildTabCoBan() {
		// common part: create layout
		tabCoBan = new VerticalLayout();
		tabCoBan.setImmediate(false);
		tabCoBan.setWidth("100.0%");
		tabCoBan.setHeight("77.94%");
		tabCoBan.setMargin(false);
		
		// txtMaGV
		txtMaGV = new TextField();
		txtMaGV.setCaption("Mã giảng viên");
		txtMaGV.setImmediate(false);
		txtMaGV.setWidth("380px");
		txtMaGV.setHeight("24px");
		txtMaGV.setSecret(false);
		tabCoBan.addComponent(txtMaGV);
		
		// txtHoTenGV
		txtHoTenGV = new TextField();
		txtHoTenGV.setCaption("Họ tên giảng viên");
		txtHoTenGV.setImmediate(false);
		txtHoTenGV.setWidth("55.68%");
		txtHoTenGV.setHeight("30px");
		txtHoTenGV.setSecret(false);
		tabCoBan.addComponent(txtHoTenGV);
		
		// txtNgaySinh
		txtNgaySinh = new PopupDateField();
		txtNgaySinh.setCaption("Ngày Sinh");
		txtNgaySinh.setImmediate(false);
		txtNgaySinh.setWidth("380px");
		txtNgaySinh.setHeight("-1px");
		txtNgaySinh.setInvalidAllowed(false);
		tabCoBan.addComponent(txtNgaySinh);
		
		// txtGioiTinh
		txtGioiTinh = new ComboBox();
		txtGioiTinh.setCaption("Giới Tính");
		txtGioiTinh.setImmediate(false);
		txtGioiTinh.setWidth("379px");
		txtGioiTinh.setHeight("-1px");
		tabCoBan.addComponent(txtGioiTinh);
		
		// txtDiaChi
		txtDiaChi = new TextField();
		txtDiaChi.setCaption("Địa chỉ");
		txtDiaChi.setImmediate(false);
		txtDiaChi.setWidth("379px");
		txtDiaChi.setHeight("-1px");
		txtDiaChi.setSecret(false);
		tabCoBan.addComponent(txtDiaChi);
		
		// txtDienThoai
		txtDienThoai = new TextField();
		txtDienThoai.setCaption("Điện Thoại");
		txtDienThoai.setImmediate(false);
		txtDienThoai.setWidth("379px");
		txtDienThoai.setHeight("-1px");
		txtDienThoai.setSecret(false);
		tabCoBan.addComponent(txtDienThoai);
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setCaption("Địa chỉ Email");
		txtEmail.setImmediate(false);
		txtEmail.setWidth("379px");
		txtEmail.setHeight("24px");
		txtEmail.setSecret(false);
		tabCoBan.addComponent(txtEmail);
		
		// txtGhiChuGV
		txtGhiChuGV = new TextArea();
		txtGhiChuGV.setCaption("Ghi Chú");
		txtGhiChuGV.setImmediate(false);
		txtGhiChuGV.setWidth("379px");
		txtGhiChuGV.setHeight("71px");
		tabCoBan.addComponent(txtGhiChuGV);
		
		return tabCoBan;
	}

	@AutoGenerated
	private VerticalLayout buildTabThongTinCongTacGV() {
		// common part: create layout
		tabThongTinCongTacGV = new VerticalLayout();
		tabThongTinCongTacGV.setImmediate(false);
		tabThongTinCongTacGV.setWidth("100.0%");
		tabThongTinCongTacGV.setHeight("73.61%");
		tabThongTinCongTacGV.setMargin(false);
		
		// txtHeSoLuongGV
		txtHeSoLuongGV = new TextField();
		txtHeSoLuongGV.setCaption("Hệ số lương");
		txtHeSoLuongGV.setImmediate(false);
		txtHeSoLuongGV.setWidth("379px");
		txtHeSoLuongGV.setHeight("24px");
		txtHeSoLuongGV.setSecret(false);
		tabThongTinCongTacGV.addComponent(txtHeSoLuongGV);
		tabThongTinCongTacGV.setComponentAlignment(txtHeSoLuongGV,
				new Alignment(33));
		
		// textBacLuong
		textBacLuong = new TextField();
		textBacLuong.setCaption("Bậc Lương");
		textBacLuong.setImmediate(false);
		textBacLuong.setWidth("379px");
		textBacLuong.setHeight("-1px");
		textBacLuong.setSecret(false);
		tabThongTinCongTacGV.addComponent(textBacLuong);
		
		// popNgayHuong
		popNgayHuong = new PopupDateField();
		popNgayHuong.setCaption("Ngày bắt đầu hưởng lương");
		popNgayHuong.setImmediate(false);
		popNgayHuong.setWidth("379px");
		popNgayHuong.setHeight("-1px");
		popNgayHuong.setInvalidAllowed(false);
		tabThongTinCongTacGV.addComponent(popNgayHuong);
		
		// comBoMon
		comBoMon = new ComboBox();
		comBoMon.setCaption("Thuộc bộ môn");
		comBoMon.setImmediate(false);
		comBoMon.setWidth("379px");
		comBoMon.setHeight("22px");
		tabThongTinCongTacGV.addComponent(comBoMon);
		
		// textKhenThuong
		textKhenThuong = new TextField();
		textKhenThuong.setCaption("Loại hình khen thưởng");
		textKhenThuong.setImmediate(false);
		textKhenThuong.setWidth("379px");
		textKhenThuong.setHeight("24px");
		textKhenThuong.setSecret(false);
		tabThongTinCongTacGV.addComponent(textKhenThuong);
		tabThongTinCongTacGV.setComponentAlignment(textKhenThuong,
				new Alignment(9));
		
		// textNoiDungKT
		textNoiDungKT = new TextField();
		textNoiDungKT.setCaption("Nội dung khen thưởng:");
		textNoiDungKT.setImmediate(false);
		textNoiDungKT.setWidth("379px");
		textNoiDungKT.setHeight("-1px");
		textNoiDungKT.setSecret(false);
		tabThongTinCongTacGV.addComponent(textNoiDungKT);
		
		// textKyLuat
		textKyLuat = new TextField();
		textKyLuat.setCaption("Loại hình kỷ luật:");
		textKyLuat.setImmediate(false);
		textKyLuat.setWidth("379px");
		textKyLuat.setHeight("-1px");
		textKyLuat.setSecret(false);
		tabThongTinCongTacGV.addComponent(textKyLuat);
		
		// textNoiDungKL
		textNoiDungKL = new TextField();
		textNoiDungKL.setCaption("Nội dung kỷ luật:");
		textNoiDungKL.setImmediate(false);
		textNoiDungKL.setWidth("379px");
		textNoiDungKL.setHeight("-1px");
		textNoiDungKL.setSecret(false);
		tabThongTinCongTacGV.addComponent(textNoiDungKL);
		
		return tabThongTinCongTacGV;
	}

	@AutoGenerated
	private TabSheet buildTabsheetHocHamHocVi() {
		// common part: create layout
		tabsheetHocHamHocVi = new TabSheet();
		tabsheetHocHamHocVi.setImmediate(true);
		tabsheetHocHamHocVi.setWidth("100.0%");
		tabsheetHocHamHocVi.setHeight("68.95%");
		
		// tabHocVi
		tabHocVi = buildTabHocVi();
		tabsheetHocHamHocVi.addTab(tabHocVi, "Học vị", null);
		
		// tabHocHam
		tabHocHam = buildTabHocHam();
		tabsheetHocHamHocVi.addTab(tabHocHam, "Học hàm", null);
		
		return tabsheetHocHamHocVi;
	}

	@AutoGenerated
	private VerticalLayout buildTabHocVi() {
		// common part: create layout
		tabHocVi = new VerticalLayout();
		tabHocVi.setImmediate(false);
		tabHocVi.setWidth("100.0%");
		tabHocVi.setHeight("74.22%");
		tabHocVi.setMargin(false);
		
		// txtTenHocVi
		txtTenHocVi = new TextField();
		txtTenHocVi.setCaption("Tên học vị");
		txtTenHocVi.setImmediate(false);
		txtTenHocVi.setWidth("375px");
		txtTenHocVi.setHeight("-1px");
		txtTenHocVi.setSecret(false);
		tabHocVi.addComponent(txtTenHocVi);
		
		// txtTenTruongDT
		txtTenTruongDT = new TextField();
		txtTenTruongDT.setCaption("Trường đào tạo");
		txtTenTruongDT.setImmediate(false);
		txtTenTruongDT.setWidth("378px");
		txtTenTruongDT.setHeight("-1px");
		txtTenTruongDT.setSecret(false);
		tabHocVi.addComponent(txtTenTruongDT);
		
		// popNgayBD
		popNgayBD = new PopupDateField();
		popNgayBD.setCaption("Ngày bắt đầu");
		popNgayBD.setImmediate(false);
		popNgayBD.setWidth("378px");
		popNgayBD.setHeight("-1px");
		popNgayBD.setInvalidAllowed(false);
		tabHocVi.addComponent(popNgayBD);
		
		// popNgayKT
		popNgayKT = new PopupDateField();
		popNgayKT.setCaption("Ngày kết thúc");
		popNgayKT.setImmediate(false);
		popNgayKT.setWidth("375px");
		popNgayKT.setHeight("-1px");
		popNgayKT.setInvalidAllowed(false);
		tabHocVi.addComponent(popNgayKT);
		
		// txtDiaChiTruongDT
		txtDiaChiTruongDT = new TextField();
		txtDiaChiTruongDT.setCaption("Địa chỉ trường đào tạo");
		txtDiaChiTruongDT.setImmediate(false);
		txtDiaChiTruongDT.setWidth("378px");
		txtDiaChiTruongDT.setHeight("-1px");
		txtDiaChiTruongDT.setSecret(false);
		tabHocVi.addComponent(txtDiaChiTruongDT);
		
		return tabHocVi;
	}

	@AutoGenerated
	private VerticalLayout buildTabHocHam() {
		// common part: create layout
		tabHocHam = new VerticalLayout();
		tabHocHam.setImmediate(false);
		tabHocHam.setWidth("738px");
		tabHocHam.setHeight("196px");
		tabHocHam.setMargin(false);
		
		// txtTenHocHam
		txtTenHocHam = new TextField();
		txtTenHocHam.setCaption("Tên học hàm");
		txtTenHocHam.setImmediate(false);
		txtTenHocHam.setWidth("378px");
		txtTenHocHam.setHeight("-1px");
		txtTenHocHam.setSecret(false);
		tabHocHam.addComponent(txtTenHocHam);
		
		// popThoiGianDat
		popThoiGianDat = new PopupDateField();
		popThoiGianDat.setCaption("Thời gian đạt");
		popThoiGianDat.setImmediate(false);
		popThoiGianDat.setWidth("378px");
		popThoiGianDat.setHeight("-1px");
		popThoiGianDat.setInvalidAllowed(false);
		tabHocHam.addComponent(popThoiGianDat);
		
		// txtDienGiai
		txtDienGiai = new TextArea();
		txtDienGiai.setCaption("Diễn giải");
		txtDienGiai.setImmediate(false);
		txtDienGiai.setWidth("518px");
		txtDienGiai.setHeight("-1px");
		tabHocHam.addComponent(txtDienGiai);
		
		return tabHocHam;
	}

	@AutoGenerated
	private VerticalLayout buildTabNghienCuuKH() {
		// common part: create layout
		tabNghienCuuKH = new VerticalLayout();
		tabNghienCuuKH.setImmediate(false);
		tabNghienCuuKH.setWidth("100.0%");
		tabNghienCuuKH.setHeight("52.04%");
		tabNghienCuuKH.setMargin(false);
		
		// textTenCTNC
		textTenCTNC = new TextField();
		textTenCTNC.setCaption("Tên chương trình nghiên cứu");
		textTenCTNC.setImmediate(false);
		textTenCTNC.setWidth("379px");
		textTenCTNC.setHeight("-1px");
		textTenCTNC.setSecret(false);
		tabNghienCuuKH.addComponent(textTenCTNC);
		tabNghienCuuKH.setComponentAlignment(textTenCTNC, new Alignment(33));
		
		// textLoaiCTNC
		textLoaiCTNC = new TextField();
		textLoaiCTNC.setCaption("Loại chương trình nghiên cứu");
		textLoaiCTNC.setImmediate(false);
		textLoaiCTNC.setWidth("379px");
		textLoaiCTNC.setHeight("-1px");
		textLoaiCTNC.setSecret(false);
		tabNghienCuuKH.addComponent(textLoaiCTNC);
		
		// popNgayBatDau
		popNgayBatDau = new PopupDateField();
		popNgayBatDau.setCaption("Ngày bắt đầu:");
		popNgayBatDau.setImmediate(false);
		popNgayBatDau.setWidth("379px");
		popNgayBatDau.setHeight("-1px");
		popNgayBatDau.setInvalidAllowed(false);
		tabNghienCuuKH.addComponent(popNgayBatDau);
		
		// popNgayKetThuc
		popNgayKetThuc = new PopupDateField();
		popNgayKetThuc.setCaption("Ngày kết thúc:");
		popNgayKetThuc.setImmediate(false);
		popNgayKetThuc.setWidth("379px");
		popNgayKetThuc.setHeight("-1px");
		popNgayKetThuc.setInvalidAllowed(false);
		tabNghienCuuKH.addComponent(popNgayKetThuc);
		
		return tabNghienCuuKH;
	}

}
