package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.constants.cTeacherInfo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;

public class rightContentImportData extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout layoutImport;
	@AutoGenerated
	private ListSelect listHeading;
	@AutoGenerated
	private Button btnImport;
	@AutoGenerated
	private Label lblFilePath;
	@AutoGenerated
	private OptionGroup optionGroupTable;
	@AutoGenerated
	private Label label_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentImportData() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
//		optionGroupTable.setData(cTeacherInfo.IMPORT_SELECT_CHOICES) ;
		

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("520px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("520px");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("<h1> Import thong tin</h1>");
		label_2.setContentMode(3);
		mainLayout.addComponent(label_2);
		
		// optionGroupTable
		optionGroupTable = new OptionGroup("Chon bang can import", cTeacherInfo.IMPORT_SELECT_CHOICES);
		optionGroupTable.setImmediate(false);
		optionGroupTable.setWidth("380px");
		optionGroupTable.setHeight("-1px");
		mainLayout.addComponent(optionGroupTable);
		
		// layoutImport
		layoutImport = buildLayoutImport();
		mainLayout.addComponent(layoutImport);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildLayoutImport() {
		// common part: create layout
		layoutImport = new VerticalLayout();
		layoutImport.setImmediate(false);
		layoutImport.setWidth("100.0%");
		layoutImport.setHeight("-1px");
		layoutImport.setMargin(false);
		
		// lblFilePath
		lblFilePath = new Label();
		lblFilePath.setCaption("Chon file");
		lblFilePath.setImmediate(false);
		lblFilePath.setWidth("100.0%");
		lblFilePath.setHeight("-1px");
		lblFilePath
				.setValue("<input class=\"gwt-FileUpload\" type=\"file\" name=\"PID64_file\"/>");
		lblFilePath.setContentMode(3);
		layoutImport.addComponent(lblFilePath);
		
		// btnImport
		btnImport = new Button();
		btnImport.setCaption("Import");
		btnImport.setImmediate(false);
		btnImport.setWidth("-1px");
		btnImport.setHeight("-1px");
		layoutImport.addComponent(btnImport);
		
		// listHeading
		listHeading = new ListSelect();
		listHeading.setCaption("File can import co cac cot theo thu tu sau ");
		listHeading.setImmediate(false);
		listHeading.setWidth("100.0%");
		listHeading.setHeight("-1px");
		layoutImport.addComponent(listHeading);
		
		return layoutImport;
	}

}
