package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.constants.Constants;
import cit.group10.qlGiangvien.detailedInfo.*;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

public class rightContentRegistedResearching extends CustomComponent implements Constants {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btnApply, btnReset;
	@AutoGenerated
	private TextArea txtContent;
	
	@AutoGenerated
	private ComboBox comboBoxCap;
	@AutoGenerated
	private PopupDateField txtNgayKT;
	@AutoGenerated
	private PopupDateField txtNgayBD;
	@AutoGenerated
	private TextArea txtName;
	@AutoGenerated
	private Label lblTitle;
	
	private TextField txtMaDeTaiNC;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentRegistedResearching() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		btnApply.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
//				beans.addBean(new TeacherBean()) ;
				getDataNC() ;
				
			}
		});
		
		btnReset.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
//				beans.addBean(new TeacherBean()) ;
				resetDataNC() ;
				
			}
		});
		
		
		
		
		
	}
	
	//=============================RESET AND GET DATA
	
	private void resetDataNC(){
		
//		txtMaDeTaiNC
//		txtName
//		txtNgayKT
//		txtNgayBD
//		txtContent
//		comboBoxCap
		
		
	}
	
	private String getDataNC(){
		
		String sql = "insert " ;
//		sql += txtMaDeTaiNC
//		txtName
//		txtNgayKT
//		txtNgayBD
//		txtContent
//		comboBoxCap
		
		System.out.println(sql) ;
		return sql ;
		
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("632px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("632px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("<center><h1>Dang ky de tai nghien cuu</h1></center>");
		lblTitle.setContentMode(3);
		mainLayout.addComponent(lblTitle);
		
		
		//txtMaDeTaiNC
		txtMaDeTaiNC= new TextField();
		txtMaDeTaiNC.setCaption("Ma de tai");
		txtMaDeTaiNC.setImmediate(false);
		txtMaDeTaiNC.setWidth("100.0%");
		txtMaDeTaiNC.setHeight("-1px");
		mainLayout.addComponent(txtMaDeTaiNC);
		
		
		
		// txtName
		txtName = new TextArea();
		txtName.setCaption("Ten de tai");
		txtName.setImmediate(false);
		txtName.setWidth("100.0%");
		txtName.setHeight("65px");
		mainLayout.addComponent(txtName);
		
		// popupDateStartedDay
		txtNgayBD = new PopupDateField();
		txtNgayBD.setCaption("Ngay Bat Dau :");
		txtNgayBD.setImmediate(false);
		txtNgayBD.setWidth("300px");
		txtNgayBD.setHeight("-1px");
		txtNgayBD.setInvalidAllowed(false);
		mainLayout.addComponent(txtNgayBD);
		
		// popupDateEndedDay
		txtNgayKT = new PopupDateField();
		txtNgayKT.setCaption("Ngay Ket Thuc :");
		txtNgayKT.setImmediate(false);
		txtNgayKT.setWidth("300px");
		txtNgayKT.setHeight("-1px");
		txtNgayKT.setInvalidAllowed(false);
		mainLayout.addComponent(txtNgayKT);
		
		// comboBoxStatus
		comboBoxCap = new ComboBox("Pham Vi :", LIST_PHAMVI);
		comboBoxCap.select(S_PHAMVI[0]) ;
//		comboBoxCap.setCaption("Status :");
		comboBoxCap.setImmediate(false);
		comboBoxCap.setWidth("300px");
		comboBoxCap.setHeight("-1px");
		mainLayout.addComponent(comboBoxCap);
		
		
		// txtContent
		txtContent = new TextArea();
		txtContent.setCaption("Noi dung thuc hien");
		txtContent.setImmediate(false);
		txtContent.setWidth("100.0%");
		txtContent.setHeight("-1px");
		mainLayout.addComponent(txtContent);
		
		// btnApply
		btnApply = new Button();
		btnApply.setCaption("Them ");
		btnApply.setImmediate(true);
		btnApply.setWidth("100px");
		btnApply.setHeight("-1px");
		mainLayout.addComponent(btnApply);
		
		
		//btnReset
		btnReset = new Button();
		btnReset.setCaption("Reset");
		btnReset.setImmediate(true);
		btnReset.setWidth("100px");
		btnReset.setHeight("-1px");
		mainLayout.addComponent(btnReset);
		
		return mainLayout;
	}

	

}
