package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class rightContentAddInfoGV extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheetInfoGV;
	@AutoGenerated
	private HorizontalLayout tabNghienCuu;
	@AutoGenerated
	private HorizontalLayout tabHocHamHocVi;
	@AutoGenerated
	private TabSheet tabsheetHocHamHocVi;
	@AutoGenerated
	private VerticalLayout tabHocHam;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private HorizontalLayout tabCongTac;
	@AutoGenerated
	private VerticalLayout tabCoBan;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btnApply;
	@AutoGenerated
	private Button btnDelete;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentAddInfoGV() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("-1px");
		label_1.setValue("<h1>thong tin </h1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(6));
		
		// tabSheetInfoGV
		tabSheetInfoGV = buildTabSheetInfoGV();
		mainLayout.addComponent(tabSheetInfoGV);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// btnDelete
		btnDelete = new Button();
		btnDelete.setCaption("Delete");
		btnDelete.setImmediate(false);
		btnDelete.setWidth("-1px");
		btnDelete.setHeight("-1px");
		horizontalLayout_1.addComponent(btnDelete);
		horizontalLayout_1.setComponentAlignment(btnDelete, new Alignment(6));
		
		// btnApply
		btnApply = new Button();
		btnApply.setCaption("Apply");
		btnApply.setImmediate(false);
		btnApply.setWidth("-1px");
		btnApply.setHeight("-1px");
		horizontalLayout_1.addComponent(btnApply);
		horizontalLayout_1.setComponentAlignment(btnApply, new Alignment(6));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private TabSheet buildTabSheetInfoGV() {
		// common part: create layout
		tabSheetInfoGV = new TabSheet();
		tabSheetInfoGV.setImmediate(true);
		tabSheetInfoGV.setWidth("100.0%");
		tabSheetInfoGV.setHeight("521px");
		
		// tabCoBan
		tabCoBan = new VerticalLayout();
		tabCoBan.setImmediate(false);
		tabCoBan.setWidth("100.0%");
		tabCoBan.setHeight("100.0%");
		tabCoBan.setMargin(false);
		tabSheetInfoGV.addTab(tabCoBan, "Thong Tin Co ban", null);
		
		// tabCongTac
		tabCongTac = new HorizontalLayout();
		tabCongTac.setImmediate(false);
		tabCongTac.setWidth("100.0%");
		tabCongTac.setHeight("100.0%");
		tabCongTac.setMargin(false);
		tabSheetInfoGV.addTab(tabCongTac, "THong tin cong tac", null);
		
		// tabHocHamHocVi
		tabHocHamHocVi = buildTabHocHamHocVi();
		tabSheetInfoGV.addTab(tabHocHamHocVi, "Hoc Ham, Hoc vi", null);
		
		// tabNghienCuu
		tabNghienCuu = new HorizontalLayout();
		tabNghienCuu.setImmediate(false);
		tabNghienCuu.setWidth("100.0%");
		tabNghienCuu.setHeight("100.0%");
		tabNghienCuu.setMargin(false);
		tabSheetInfoGV.addTab(tabNghienCuu, "Nghien Cuu Khoa Hoc", null);
		
		return tabSheetInfoGV;
	}

	@AutoGenerated
	private HorizontalLayout buildTabHocHamHocVi() {
		// common part: create layout
		tabHocHamHocVi = new HorizontalLayout();
		tabHocHamHocVi.setImmediate(false);
		tabHocHamHocVi.setWidth("100.0%");
		tabHocHamHocVi.setHeight("100.0%");
		tabHocHamHocVi.setMargin(false);
		
		// tabsheetHocHamHocVi
		tabsheetHocHamHocVi = buildTabsheetHocHamHocVi();
		tabHocHamHocVi.addComponent(tabsheetHocHamHocVi);
		
		return tabHocHamHocVi;
	}

	@AutoGenerated
	private TabSheet buildTabsheetHocHamHocVi() {
		// common part: create layout
		tabsheetHocHamHocVi = new TabSheet();
		tabsheetHocHamHocVi.setImmediate(true);
		tabsheetHocHamHocVi.setWidth("100.0%");
		tabsheetHocHamHocVi.setHeight("100.0%");
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		tabsheetHocHamHocVi.addTab(verticalLayout_3, "Hoc Vi", null);
		
		// tabHocHam
		tabHocHam = new VerticalLayout();
		tabHocHam.setImmediate(false);
		tabHocHam.setWidth("-1px");
		tabHocHam.setHeight("-1px");
		tabHocHam.setMargin(false);
		tabsheetHocHamHocVi.addTab(tabHocHam, "Hoc Ham", null);
		
		return tabsheetHocHamHocVi;
	}

}
