package cit.group10.qlGiangvien.widgets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import cit.group10.qlGiangvien.constants.cTeacherInfo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;


public class rightContentImportData extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout layoutImport;
	@AutoGenerated
	private ListSelect listHeading;
	@AutoGenerated
	private Button btnImport;
	@AutoGenerated
	private Label lblFilePath;
	@AutoGenerated
	private OptionGroup optionGroupTable;
	@AutoGenerated
	private Label label_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
	static final String DB_URL = "jdbc:mysql://localhost/dbqlGiangvien" ;
	static final String USER = "root";
	static final String PASS = "root";
	public rightContentImportData() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
//		optionGroupTable.setData(cTeacherInfo.IMPORT_SELECT_CHOICES) ;
		

		// TODO add user code here
		btnImport.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
				  String newValue ="null";
				  System.out.println("Test button click event") ;
				  listHeading.setValue(newValue);
				
			}
		});
	
	}
	private void ImportData()
	{
		Connection conn = null;
	    Statement stmt = null;
	      try{
	
	       Class.forName("com.mysql.jdbc.Driver");
	       conn = DriverManager.getConnection(DB_URL,USER,PASS);
	       stmt = conn.createStatement();
	
			String s1 =  lblFilePath.getValue().toString();
			String t1=null;
			if(optionGroupTable.getValue().equals(cTeacherInfo.IMPORT_SELECT_CHOICES.contains("  Bộ môn")))
			{
					t1 = "LOAD DATA LOCAL INFILE 's1' INTO TABLE BoMon";
					int r2 =stmt.executeUpdate(t1) ;
			}
			else 
				
			 
	         System.out.println("Import into database :"+ t1) ;
	       				
	         
	         ResultSet rs = stmt.executeQuery(t1);

	          rs.close();	//Đóng cơ sở dữ liệu
	         stmt.close();
	         conn.close();
	    } catch(Exception ex){
	       
	    	System.out.println("SQLException: " + ex.getMessage());
		 }
		
		
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("520px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("520px");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("<h1> Import thông tin </h1>");
		label_2.setContentMode(3);
		mainLayout.addComponent(label_2);
		
				
		// optionGroupTable
		optionGroupTable = new OptionGroup("Chọn bảng cần import", cTeacherInfo.IMPORT_SELECT_CHOICES);
		optionGroupTable.setImmediate(false);
		optionGroupTable.setWidth("380px");
		optionGroupTable.setHeight("-1px");
		mainLayout.addComponent(optionGroupTable);
		
		// layoutImport
		layoutImport = buildLayoutImport();
		mainLayout.addComponent(layoutImport);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildLayoutImport() {
		// common part: create layout
		layoutImport = new VerticalLayout();
		layoutImport.setImmediate(false);
		layoutImport.setWidth("100.0%");
		layoutImport.setHeight("-1px");
		layoutImport.setMargin(false);
		
		// lblFilePath
		lblFilePath = new Label();
		lblFilePath.setCaption("Chon file");
		lblFilePath.setImmediate(false);
		lblFilePath.setWidth("100.0%");
		lblFilePath.setHeight("-1px");
		lblFilePath
				.setValue("<input class=\"gwt-FileUpload\" type=\"file\" name=\"PID64_file\"/>");
		lblFilePath.setContentMode(3);
		layoutImport.addComponent(lblFilePath);
		
		// btnImport
		btnImport = new Button();
		btnImport.setCaption("Import");
		btnImport.setImmediate(false);
		btnImport.setWidth("-1px");
		btnImport.setHeight("-1px");
		layoutImport.addComponent(btnImport);
		
		// listHeading
		listHeading = new ListSelect();
		listHeading.setCaption("File can import co cac cot theo thu tu sau ");
		listHeading.setImmediate(false);
		listHeading.setWidth("100.0%");
		listHeading.setHeight("-1px");
		layoutImport.addComponent(listHeading);
		
		return layoutImport;
	}

}
