package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class rightContentKhenThuongKyLuat extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TextArea txtNoidung;
	@AutoGenerated
	private PopupDateField popupDateField_1;
	@AutoGenerated
	private ComboBox cbHinhthuc;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentKhenThuongKyLuat() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("340px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("340px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h1>thong tin khen thuong ky luat</h1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// cbHinhthuc
		cbHinhthuc = new ComboBox();
		cbHinhthuc.setCaption("hinh thuc");
		cbHinhthuc.setImmediate(false);
		cbHinhthuc.setWidth("280px");
		cbHinhthuc.setHeight("-1px");
		mainLayout.addComponent(cbHinhthuc);
		
		// popupDateField_1
		popupDateField_1 = new PopupDateField();
		popupDateField_1.setCaption("ngay thuc hien");
		popupDateField_1.setImmediate(false);
		popupDateField_1.setWidth("280px");
		popupDateField_1.setHeight("-1px");
		popupDateField_1.setInvalidAllowed(false);
		mainLayout.addComponent(popupDateField_1);
		
		// txtNoidung
		txtNoidung = new TextArea();
		txtNoidung.setCaption("noi dung");
		txtNoidung.setImmediate(false);
		txtNoidung.setWidth("100.0%");
		txtNoidung.setHeight("-1px");
		mainLayout.addComponent(txtNoidung);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("them vo");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1);
		
		return mainLayout;
	}

}
