package cit.group10.qlGiangvien.widgets;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import cit.group10.qlGiangvien.constants.cTeacherInfo;
import cit.group10.qlGiangvien.databaseConnect.GetDataFromDatabase;
import cit.group10.qlGiangvien.others.subWindow;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ConversionException;
import com.vaadin.data.Property.ReadOnlyException;
import com.vaadin.ui.AbstractSelect;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Form;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Select;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class rightContentAddNewTeacher extends CustomComponent implements cTeacherInfo {

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_2;
	@AutoGenerated
	private VerticalLayout tabsheetNghienCuuKH;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TwinColSelect twinColSelect_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private PopupDateField txtNghienCuuNgayKT;
	@AutoGenerated
	private PopupDateField txtNghienCuuNgayThamGia;
	@AutoGenerated
	private VerticalLayout tabsheetAccount;
	@AutoGenerated
	private Button btnDangNhapReset;
	@AutoGenerated
	private PasswordField txtPassword;
	@AutoGenerated
	private TextField txtUserName;
	@AutoGenerated
	private VerticalLayout tabsheetHocHamHocVi;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private VerticalLayout verticalLayoutHocHam;
	@AutoGenerated
	private Button btnHocHamReset;
	@AutoGenerated
	private PopupDateField txtHocHamNgayDatDuoc;
	@AutoGenerated
	private ComboBox txtTenHocHam;
	@AutoGenerated
	private VerticalLayout verticalLayoutHocVi;
	@AutoGenerated
	private Button btnHocViReset;
	@AutoGenerated
	private TextArea txtHocViDiaChiTruong;
	@AutoGenerated
	private PopupDateField txtHocViNgayKT;
	@AutoGenerated
	private PopupDateField txtHocViNgayBD;
	@AutoGenerated
	private TextField txtTenTruong;
	@AutoGenerated
	private ComboBox txtHocViTen;
	@AutoGenerated
	private VerticalLayout tabsheetCongTac;
	@AutoGenerated
	private Button btnCongTacReset;
	@AutoGenerated
	private VerticalLayout verticalLayoutBoMon;
	@AutoGenerated
	private PopupDateField txtBoMonNgayKT;
	@AutoGenerated
	private PopupDateField txtBoMonNgayBD;
	@AutoGenerated
	private ComboBox txtChucVu;
	@AutoGenerated
	private ComboBox txtBoMon;
	@AutoGenerated
	private ComboBox txtBacLuong;
	@AutoGenerated
	private TextField txtHeSoLuong;
	@AutoGenerated
	private PopupDateField txtCongTacNgayBD;
	@AutoGenerated
	private VerticalLayout tabsheetCoBan;
	@AutoGenerated
	private Button btnThongTInReset;
	@AutoGenerated
	private TextArea txtGhiChu;
	@AutoGenerated
	private TextArea txtDiaChi;
	@AutoGenerated
	private TextField txtThongTinEmail;
	@AutoGenerated
	private TextField txtDienThoai;
	@AutoGenerated
	private PopupDateField txtNgaySinh;
	@AutoGenerated
	private OptionGroup txtGioiTinh;
	@AutoGenerated
	private TextField txtHoTen;
	@AutoGenerated
	private TextField txtMaGV;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button btnResetAll;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private Label label_1;
	
	private VerticalLayout verticalShowInfo;
	private Table tbHocVi, tbHocHam, tbNghienCuu ;
	
	

	
//	Form form ;
	private int func =0 ;
	
	
		public rightContentAddNewTeacher(int function) {
		this.func =function ;
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		
		
		
	}
	//===================================================RESET DATA
	private void resetCoBan(){
		
		txtMaGV.setValue("") ;
		txtHoTen.setValue("") ;
		txtGioiTinh.select(S_GENDER[0]) ;
		txtNgaySinh.setValue("") ;
		txtDienThoai.setValue("") ;
		txtThongTinEmail.setValue("") ;
		txtDiaChi.setValue("") ;
		txtGhiChu.setValue("") ;
	}
	
	private void resetCongTac(){
		
		txtCongTacNgayBD.setValue("") ;
		txtHeSoLuong.setValue("") ;
		txtBacLuong.select(S_BACLUONG[0]) ;
//		txtBoMon
		txtChucVu.select(S_CHUCVU[0]) ;
		txtBoMonNgayBD.setValue("") ;
		txtBoMonNgayKT.setValue("") ;
	}
	
	private void resetHocVi(){
		
		txtHocViTen.select(S_HOCVI[0]) ;
		txtTenTruong.setValue("") ;
		txtHocViNgayBD.setValue("") ;
		txtHocViNgayKT.setValue("") ;
		txtHocViDiaChiTruong.setValue("") ;
		
	}
	
	private void resetHocHam(){
		
		txtTenHocHam.select(S_HOCHAM[0]) ;
		txtHocHamNgayDatDuoc.setValue("") ;
		
	}
	
	private void resetDangNhap(){
		
		txtUserName.setValue("") ;
		txtPassword.setValue("") ;
	}
	
//	private void resetNghienCuu(){
//		
////		twinColSelect_1
//		txtNghienCuuNgayThamGia.setValue("") ;
//		txtNghienCuuNgayKT.setValue("") ;
//	}
	
	
	//===================================================get DATA
	private void getInfo(){
		
		
		List<String> ls=new ArrayList<String>();
		
		String err_t ="" ;
		
		try {
			boolean flag =true;
			String s1 = getCoBan();    if (!s1.equals("0")) ls.add(s1) ; else  { flag=false; err_t += "Thong Tin Co Ban \n" ;} 
			String s2 = getCongTac() ; if (!s2.equals("0"))  ls.add(s2); else { flag=false; err_t += "Thong Tin Cong Tac \n" ;} 
			String s3 = getGV_BoMon(); if (!s3.equals("0")) ls.add(s3); else { flag=false; err_t += "Thong Tin Bo Mon \n" ;}
			String s4 = getHocVi();    if (!s4.equals("0")) ls.add(s4) ; else { flag=false; err_t += "Thong Tin Hoc Vi \n" ;}
			String s5 = getHocHam();   if (!s5.equals("0")) ls.add(s5) ;
			String s6 = getDangNhap(); if (!s6.equals("0")) ls.add(s6) ; else { flag=false; err_t += "Thong Tin Dang Nhap \n" ;} 
			String s7 = getNghienCuu();if (!s7.equals("0")) ls.add(getNghienCuu()) ;
			
			if (!flag){
				
				Window subwindow = subWindow.confirmDelete("Xac nhan", "Vui long dien day du thong tin trong cac tab: "+err_t , "Ok") ;
				if (subwindow.getParent() == null) {
		            
		            getWindow().addWindow(subwindow);
		        }
				
				return ;
			}
			
		} catch (Exception e) {
			getWindow().showNotification("Vui long dien day du thong tin") ;
			System.out.println("error in insert :"+ e.toString()) ;
			e.printStackTrace() ;
			return ;
		}
		
		
		boolean re = GetDataFromDatabase.insertGiangVien(ls) ;
		String content = re ? "thanh cong" : "that bai" ;
		
		
		Window subwindow = subWindow.confirmDelete("Xac nhan", content, "Ok") ;
		if (subwindow.getParent() == null) {
            
            getWindow().addWindow(subwindow);
        }
		
	}//getInfo
	
	private void getUpdateInfo(){
		
		
		List<String> ls=new ArrayList<String>();
		
		String err_t ="" ;
		
		try {
			boolean flag =true;
			String s1 = getUpdateCoBan();    if (!s1.equals("0")) ls.add(s1) ; else  { flag=false; err_t += "Thong Tin Co Ban \n" ;} 
			String s2 = getUpdateCongTac() ; if (!s2.equals("0"))  ls.add(s2); else { flag=false; err_t += "Thong Tin Cong Tac \n" ;} 
			String s3 = getUpdateBoMon(); if (!s3.equals("0")) ls.add(s3); else { flag=false; err_t += "Thong Tin Bo Mon \n" ;}
			String s4 = getHocVi();    if (!s4.equals("0")) ls.add(s4) ; else { flag=false; err_t += "Thong Tin Hoc Vi \n" ;}
			String s5 = getHocHam();   if (!s5.equals("0")) ls.add(s5) ;
			String s6 = getUpdateDangNhap(); if (!s6.equals("0")) ls.add(s6) ; else { flag=false; err_t += "Thong Tin Dang Nhap \n" ;} 
			String s7 = getNghienCuu();if (!s7.equals("0")) ls.add(getNghienCuu()) ;
			
			if (!flag){
				
				Window subwindow = subWindow.confirmDelete("Xac nhan", "Vui long dien day du thong tin trong cac tab: "+err_t , "Ok") ;
				if (subwindow.getParent() == null) {
		            
		            getWindow().addWindow(subwindow);
		        }
				
				return ;
			}
			
		} catch (Exception e) {
			getWindow().showNotification("Vui long dien day du thong tin") ;
			System.out.println("error in insert :"+ e.toString()) ;
			e.printStackTrace() ;
			return ;
		}
		
		
		boolean re = GetDataFromDatabase.insertGiangVien(ls) ;
		String content = re ? "thanh cong" : "that bai" ;
		
		
		Window subwindow = subWindow.confirmDelete("Xac nhan", content, "Ok") ;
		if (subwindow.getParent() == null) {
            
            getWindow().addWindow(subwindow);
        }
		
		
		
	}
	
	
	
	
	
	
	private void updateInfo(){
		
		getUpdateCoBan() ;
		getUpdateCongTac() ;
//		getUpdateHocVi() ;
//		getUpdateHocHam() ;
		getUpdateDangNhap() ;
//		getUpdateNghienCuu() ;

	}
	
	
	private String getCoBan(){
		
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ns ;
		try {
			if (txtMaGV.getValue().toString().length()==0 ) return "0" ;
			if (txtHoTen.getValue().toString().length()==0 ) return "0" ;			
			
			try {
				
				ns = dateFormatter.format(txtNgaySinh.getValue()) ;
				
			} catch (Exception e) {				
				return "0" ;
			}
		} catch (Exception e1) {
			return "0" ;
		}
		
		//print sql
		
		try {
			String sql = "insert into GiangVien values (";
			
			sql += "'" + txtMaGV.getValue().toString() + "' ,";
			sql += "'" + txtHoTen.getValue().toString()  + "' ," ;
			sql += " '" + ns + "', ";		
			sql += "'" + txtGioiTinh.getValue().toString() + "' ," ;		
			sql += "'" + txtDienThoai.getValue().toString() + "' ," ;
			sql += "'" + txtThongTinEmail.getValue().toString() + "' ," ;
			sql += "'" + txtDiaChi.getValue().toString() + "' ,";
			sql += "'" + txtGhiChu.getValue() + "' );" ; 
			System.out.println("Co ban : "+sql) ;
			return sql ;
		} catch (Exception e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();
			return "0" ;
		}
	}
	
	private String getUpdateCoBan() {

		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ns, sql ;
		try {
			if (txtMaGV.getValue().toString().length()==0 ) return "0" ;
			if (txtHoTen.getValue().toString().length()==0 ) return "0" ;			
			
			try {
				
				ns = dateFormatter.format(txtNgaySinh.getValue()) ;
				
			} catch (Exception e) {				
				return "0" ;
			}
		} catch (Exception e1) {
			return "0" ;
		}
		try {

			sql = "update GiangVien set ";
			
			sql += "HoTen='" + txtHoTen.getValue().toString() + "' ,";
			sql += "GioiTinh='" + txtGioiTinh.getValue().toString() + "' ,";

			sql += "NgaySinh='"	+ ns + "', ";
			
			sql += "DienThoai='" + txtDienThoai.getValue().toString() + "' ,";
			sql += "Email='" + txtThongTinEmail.getValue().toString() + "' ,";
			sql += "DiaChi='" + txtDiaChi.getValue().toString() + "' ,";
			sql += "GhiChu='" + txtGhiChu.getValue() +"' ";

			sql += " where MaGV = '" + txtMaGV.getValue().toString() + "' ;";
			
			System.out.println(sql);
			return sql;
		} catch (Exception e) {

			System.out.println("rightContentAddNewTeacher: " + e.toString());
			e.printStackTrace() ;
			return "0";
		}
	}

	private String getCongTac() {
		
		String ngayBD ;
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		
		try {
			if (txtHeSoLuong.getValue().toString().length()==0 ) return "0" ;
			if (txtBacLuong.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtCongTacNgayBD.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}
		} catch (Exception e1) {
//			e1.printStackTrace();
			return "0" ;
		}
		
		try {
			String sql = "insert into QuaTrinhCongTac(MaGV, HSLuong,Bac, NgayBD) values (";		
			
			sql +=  " '"+ txtMaGV.getValue().toString() + "',";
			sql +=  txtHeSoLuong.getValue().toString() + ",";
			sql +=  txtBacLuong.getValue().toString() +  ",";
			sql += " '" + ngayBD + "' ) ;";		
			System.out.println("cong tac : " + sql);
			return sql ;
		} catch (Exception e) {
//			e.printStackTrace();
			return "0";
		}
	}
	
	
	private String getGV_BoMon() {

		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ngayBD ;
		try {
			if (txtBoMon.getValue().toString().length()==0 ) return "0" ;
			if (txtChucVu.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtBoMonNgayBD.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}		
			
			
		} catch (Exception e1) {
//			e1.printStackTrace();
			return "0" ;
		}
		
			
			try {
				String sql = "insert into GiangVien_BoMon(MaBM, MaGV, TenCV, NgayBD, NgayKT) values (";
						
				sql += "'" + txtBoMon.getValue().toString() + "' ,";
				sql += "'" + txtMaGV.getValue().toString() + "' ,";
				sql += "'" + txtChucVu.getValue().toString() + "' ,";			
				sql += " '" + ngayBD + "' ,";
				
				try {
					sql += " '" + dateFormatter.format(txtBoMonNgayKT.getValue()) + "' ) ;";
				} catch (Exception e) {
//					e.printStackTrace() ;			
					sql += "null" + ");";
				}		
				System.out.println("cong tac : " + sql);
				return sql ;
			} catch (Exception e) {
				// TODO Auto-generated catch block
//				e.printStackTrace();
				return "0";
			}
//		
	}
	
	
	

	private String getUpdateCongTac() {
		
		String ngayBD ;
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		
		try {
			if (txtHeSoLuong.getValue().toString().length()==0 ) return "0" ;
			if (txtBacLuong.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtCongTacNgayBD.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}
		} catch (Exception e1) {
//			e1.printStackTrace();
			return "0" ;
		}
		
		
		String sql1;
	
		sql1 = "update QuaTrinhCongTac set ";

		sql1 += "HSLuong=" + txtHeSoLuong.getValue().toString() + " ,";
		sql1 += "Bac=" + txtBacLuong.getValue().toString() + " ,";
		sql1 += "NgayBD='" + ngayBD + "' ";
		sql1 += "where MaGV='" + txtMaGV.getValue().toString() + "' ;" ;
		
		System.out.println("cong tac : " + sql1);
		
		return sql1 ;
	}
	
	private String getUpdateBoMon() {
		
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ngayBD ;
		try {
			if (txtBoMon.getValue().toString().length()==0 ) return "0" ;
			if (txtChucVu.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtBoMonNgayBD.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}		
			
			
		} catch (Exception e1) {
//			e1.printStackTrace();
			return "0" ;
		}
		
		String sql2;
		sql2 = "update GiangVien_BoMon set ";

		sql2 += "TenCV='" + txtChucVu.getValue().toString() + "' ,";
		sql2 += "NgayBD='" + ngayBD + "', ";
		
		try {
			sql2 += "NgayKT='" + dateFormatter.format(txtBoMonNgayKT.getValue()) + "' ";
		} catch (Exception e) {
			// TODO Auto-generated catch block
			sql2 += "NgayKT=" + null ;
		}
		sql2 += " where MaGV='" + txtMaGV.getValue().toString() + "' ;" ;
		System.out.println("cong tac : " + sql2);
		return sql2;
	}
	
	
	

	private String getHocVi() {

		
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ngayBD, ngayKT ;
		try {
			if (txtHocViTen.getValue().toString().length()==0 ) return "0" ;
			if (txtTenTruong.getValue().toString().length()==0 ) return "0" ;
			if (txtHocViDiaChiTruong.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtHocViNgayBD.getValue()) ;
				
			} catch (Exception e) {
				e.printStackTrace() ;
				return "0" ;
			}
			try {
				
				ngayKT = dateFormatter.format(txtHocViNgayKT.getValue()) ;
				
			} catch (Exception e) {
				e.printStackTrace() ;
				return "0" ;
			}
			
		} catch (Exception e1) {
			
			e1.printStackTrace();
			return "0" ;
		}
		
			try {
				String sql = "insert into GiangVien_HocVi(MaGV, TenHocVi,TenTruongDT, DiaChiTruongDT, ThoiGianBD, ThoiGianKT )values (";

				sql += "'" + txtMaGV.getValue().toString() + "' ,";
				sql += "'" + txtHocViTen.getValue().toString() + "' ,";
				sql += "'" + txtTenTruong.getValue().toString() + "' ,";
				sql += "'" + txtHocViDiaChiTruong.getValue().toString() + "' ,";

				
					sql += " ' " + ngayBD + " ', ";
				
					sql += " ' " + ngayKT + " ' );";
				
				
				System.out.println("Hoc vi : " + sql);
				return sql;
			} catch (Exception e) {
				// TODO Auto-generated catch block
				return "0" ;
			}
		

	}

//	private String getUpdateHocVi() {
//
//		String sql;
//		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
//		try {
//
//			sql = "update GiangVien_HocVi set ";
//
//			sql += "TenHocVi='" + txtHocViTen.getValue().toString() + "' ,";
//			sql += "TenTruongDT='" + txtTenTruong.getValue().toString() + "' ,";
//
//			try {
//				sql += "ThoiGianBD=' "
//						+ dateFormatter.format(txtHocViNgayBD.getValue())
//						+ " ', ";
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				sql += "ThoiGianBD=" + null + ",";
//			}
//
//			try {
//				sql += "ThoiGianKT=' "
//						+ dateFormatter.format(txtHocViNgayKT.getValue())
//						+ " ', ";
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				sql += "ThoiGianKT" + null + ",";
//			}
//			sql += "DiaChiTruongDT='"
//					+ txtHocViDiaChiTruong.getValue().toString() + "' ,";
//			System.out.println("Hoc vi : " + sql);
//			return sql;
//		} catch (Exception e) {
//
//			System.out.println("rightContentAddNewTeacher: " + e.toString());
//			return "";
//		}
//	}

	//
	private String getHocHam() {
		
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ngayBD ;
		try {
			if (txtTenHocHam.getValue().toString().length()==0 ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtHocHamNgayDatDuoc.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}
		} catch (Exception e1) {
			
//			e1.printStackTrace();
			return "0" ;
		}
		///print sql
			try {
				String sql = "insert into GiangVien_HocHam(MaGV, TenHocHam, TGDat) values (";

				sql += "'" + txtMaGV.getValue().toString().trim() + "' ,";
				sql += "'" + txtTenHocHam.getValue().toString() + "' ,";
				sql += " '" + ngayBD + " '); ";

				System.out.println("Hoc ham : " + sql);
				return sql;
			} catch (Exception e) {
				// TODO Auto-generated catch block
//				e.printStackTrace();
				return "0" ;
			}

	}

//	private String getUpdateHocHam() {
//
//		String sql;
////		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
//		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd") ;
//
//		
//		
//		
//		try {
//
//			sql = "update GiangVien_HocHam set ";
//
//			sql += "TenHocHam='" + txtTenHocHam.getValue().toString() + "' ,";
//
//			try {
//				sql += "TGDat=' "
//						+ dateFormatter.format(txtHocHamNgayDatDuoc.getValue())
//						+ " ', ";
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				sql += "null" + ",";
//			}
//
//			System.out.println("Hoc ham : " + sql);
//			return sql;
//		} catch (Exception e) {
//
//			System.out.println("rightContentAddNewTeacher: " + e.toString());
//			return "";
//		}
//	}

	//
	private String getDangNhap() {
		
		
		try {
			if (txtUserName.getValue().toString().length()==0 ) return "0" ;
			if (txtPassword.getValue().toString().length()==0 ) return "0" ;			
			
		} catch (Exception e1) {
			
//			e1.printStackTrace();
			return "0" ;
		}
		//print sql	

		try {
			String sql = "insert into Account(MaGV, username, password, role, createdDate) values (";

			sql += "'" + txtMaGV.getValue().toString() + "' ,";
			sql += "'" + txtUserName.getValue().toString() + "' ,";
			sql += "'" + txtPassword.getValue().toString() + "' ,";
			sql += "0" + ", now() ) ;";
			System.out.println("Dang nhap : " + sql);
			return sql;
		} catch (Exception e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();
			return "0" ;
		}
	}

	private String getUpdateDangNhap() {

		try {
			if (txtUserName.getValue().toString().length()==0 ) return "0" ;
			if (txtPassword.getValue().toString().length()==0 ) return "0" ;			
			
		} catch (Exception e1) {
			
//			e1.printStackTrace();
			return "0" ;
		}
		
		String sql;
		sql = "update Account set ";
		try {

			sql += "username='" + txtUserName.getValue().toString() + "' ,";
			sql += "password='" + txtPassword.getValue().toString() + "' ";
			sql += "where MaGV='" + txtMaGV.getValue().toString() + "' ;" ;
			System.out.println("Dang nhap : " + sql);
			return sql;
		} catch (Exception e) {
			System.out.println("rightContentAddNewTeacher: " + e.toString());
			return "0";
		}
	}

	//
	private String getNghienCuu() {
		
		
		//validate
		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
		String ngayBD  ;
		try {
			if (twinColSelect_1.getValue().toString().substring(1,7).equals(null) ) return "0" ;
			
			try {
				
				ngayBD = dateFormatter.format(txtNghienCuuNgayThamGia.getValue()) ;
				
			} catch (Exception e) {
//				e.printStackTrace() ;
				return "0" ;
			}
		} catch (Exception e1) {
			
//			e1.printStackTrace();
			return "0" ;
		}
		
		
		
		
		try {
			String sql = "insert into GiangVien_NghienCuuKH values (";
			
			sql += "'" + txtMaGV.getValue().toString() + "' ,";
			sql += "'" + twinColSelect_1.getValue().toString().substring(1,7) + "' ,";
			sql += "'" + ngayBD + "', ";
			
			try {
				sql += " '" + dateFormatter.format(txtNghienCuuNgayKT.getValue()) + "'); ";
			} catch (Exception e) {			
				sql += "null" + ") ;";
			}
			System.out.println("Nghien cuu : " + sql);
			return sql;
		} catch (Exception e) {
			// TODO Auto-generated catch block
//			e.printStackTrace();
			return "0" ;
		}
	}

//	private String getUpdateNghienCuu() {
//		//
//		String sql;
//		DateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd");
//		try {
//
//			sql = "update GiangVien_NghienCuuKH set ";
//			try {
//				sql += "NgayTG=' "
//						+ dateFormatter.format(txtNghienCuuNgayThamGia
//								.getValue()) + " ', ";
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				sql += "null" + ",";
//			}
//			try {
//				sql += "NgayKT=' "
//						+ dateFormatter.format(txtNghienCuuNgayKT.getValue())
//						+ " ', ";
//			} catch (Exception e) {
//				// TODO Auto-generated catch block
//				sql += "null" + ",";
//			}
//			System.out.println("Nghien cuu : " + sql);
//			return sql;
//		} catch (Exception e) {
//
//			System.out.println("rightContentAddNewTeacher: " + e.toString());
//			return "";
//		}
//	}

	//===================================================set value for modify
	public void setUpdateData(String maGV){
				
		try {
			Item coban=GetDataFromDatabase.getDataGVCoBan(maGV) ;
			Item bomon=GetDataFromDatabase.getDataGVBoMon(maGV) ;
			Item congtac=GetDataFromDatabase.getDataGVCongTac(maGV) ;
			Item dangnhap=GetDataFromDatabase.getDataGVDangNhap(maGV) ;
			System.out.println("rightContent >> setUpdateData :" +maGV + "=="+ coban.toString()) ;
			System.out.println("rightContent >> setUpdateData :" +maGV + "=="+ bomon.toString()) ;
			System.out.println("rightContent >> setUpdateData :" +maGV + "=="+ congtac.toString()) ;
			System.out.println("rightContent >> setUpdateData :" +maGV + "=="+ dangnhap.toString()) ;
			
			verticalShowInfo.setVisible(true) ;
			tbHocVi.setContainerDataSource(GetDataFromDatabase.getDataGVHocVi(maGV)) ;
			tbHocHam.setContainerDataSource(GetDataFromDatabase.getDataGVHocHam(maGV)) ;
			tbNghienCuu.setContainerDataSource(GetDataFromDatabase.getDataGVNghienCuu(maGV)) ;
			
			txtMaGV.setValue(coban.getItemProperty("MaGV").getValue().toString()) ;
			txtMaGV.setEnabled(false) ;
			txtHoTen.setValue(coban.getItemProperty("HoTen").getValue().toString()) ;
			txtGioiTinh.select(coban.getItemProperty("GioiTinh").getValue().toString()) ;
//		txtNgaySinh.setValue(new Date(coban.getItemProperty("NgaySinh").getValue().toString())) ;
			txtDienThoai.setValue(coban.getItemProperty("DienThoai").getValue().toString()) ;
			txtThongTinEmail.setValue(coban.getItemProperty("Email").getValue().toString()) ;
			txtDiaChi.setValue(coban.getItemProperty("DiaChi").getValue().toString()) ;
			txtGhiChu.setValue(coban.getItemProperty("GhiChu").getValue().toString()) ;
			
			
//		txtCongTacNgayBD.setValue(congtac.getItemProperty("NgayBD").getValue().toString()) ;
			txtHeSoLuong.setValue(congtac.getItemProperty("HSLuong").getValue().toString()) ;
			txtBacLuong.select(congtac.getItemProperty("Bac").getValue().toString()) ;
//		txtBoMon.select(congtac.getItemProperty("MaBM").getValue().toString()) ;
			txtChucVu.select(bomon.getItemProperty("TenCV").getValue().toString()) ;
//		txtBoMonNgayBD.setValue(bomon.getItemProperty("NgayBD").getValue().toString()) ;
//		txtBoMonNgayKT.setValue(bomon.getItemProperty("NgayKT").getValue().toString()) ;
			

			txtUserName.setValue(dangnhap.getItemProperty("username").getValue().toString()) ;
			txtPassword.setValue(dangnhap.getItemProperty("password").getValue().toString()) ;
		} catch (ReadOnlyException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ConversionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		
		
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	//===================================================for build interface

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("100.0%");
		label_1.setHeight("50px");
		
		if (func==0) label_1.setValue("<h1> Them Thong Tin Giang Vien</h1>");
		else label_1.setValue("<h1> Chinh Sua Thong Tin Giang Vien</h1>");
		
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
		mainLayout.addComponent(tabSheet_2);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setSpacing(true) ;
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(true);
		
		// btnAdd
		btnAdd = new Button();
		
		if (func==0) btnAdd.setCaption("Them Giang Vien"); else btnAdd.setCaption("Cap nhat thong tin"); 
		btnAdd.setImmediate(true);
		btnAdd.setWidth("-1px");
		btnAdd.setHeight("-1px");
		horizontalLayout_2.addComponent(btnAdd);
		btnAdd.addListener(new Button.ClickListener() {			
			
			@Override
			public void buttonClick(com.vaadin.ui.Button.ClickEvent event) {

				try{
					
					if (func==0) getInfo() ;// else 
					else getUpdateInfo() ;
//						
									
				}
				catch(Exception e){ 
					getWindow().showNotification("eer in click button") ;
					System.out.println("rightContentAddNewTeacher:"+e.toString()) ;
					}
			}
		});
		
		
		
		
		
		
		// btnResetAll
		btnResetAll = new Button();
		btnResetAll.setCaption("Reset All");
		btnResetAll.setImmediate(true);
		btnResetAll.setWidth("-1px");
		btnResetAll.setHeight("-1px");
		horizontalLayout_2.addComponent(btnResetAll);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(true);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("-1px");
		
		// tabsheetCoBan
		tabsheetCoBan = buildTabsheetCoBan();
		tabSheet_2.addTab(tabsheetCoBan, "*Thong tin co ban", null);
		
		// tabsheetCongTac
		tabsheetCongTac = buildTabsheetCongTac();
		tabSheet_2.addTab(tabsheetCongTac, "*Thong tin cong tac ", null);
		
		// tabsheetHocHamHocVi
		tabsheetHocHamHocVi = buildTabsheetHocHamHocVi();
		tabSheet_2.addTab(tabsheetHocHamHocVi, "*Hoc Ham, Hoc Vi", null);
		
		// tabsheetAccount
		tabsheetAccount = buildTabsheetAccount();
		tabSheet_2.addTab(tabsheetAccount, "*Thong tin dang nhap", null);
		
		// tabsheetNghienCuuKH
		tabsheetNghienCuuKH = buildTabsheetNghienCuuKH();
		tabSheet_2.addTab(tabsheetNghienCuuKH, "Nghien Cuu Khoa Hoc", null);
		
		verticalShowInfo = buildVerticalLayoutShowInfo();
		tabSheet_2.addTab(verticalShowInfo, "Thong Tin Lien Quan", null);
		
		return tabSheet_2;
	}

	@AutoGenerated
	private VerticalLayout buildTabsheetCoBan() {
		// common part: create layout
		tabsheetCoBan = new VerticalLayout();
		tabsheetCoBan.setImmediate(false);
		tabsheetCoBan.setWidth("100.0%");
		tabsheetCoBan.setHeight("-1px");
		tabsheetCoBan.setMargin(true);
		tabsheetCoBan.setSpacing(true);
		
		// txtMaGV
		txtMaGV = new TextField();
		txtMaGV.setCaption("Ma Giang Vien:");
		txtMaGV.setImmediate(false);
		txtMaGV.setWidth("481px");
		txtMaGV.setHeight("-1px");
		if (func==0) txtMaGV.setValue(GetDataFromDatabase.getMaGV()) ; 
		tabsheetCoBan.addComponent(txtMaGV);
		
		// txtHoTen
		txtHoTen = new TextField();
		txtHoTen.setCaption("Ho Ten :");
		txtHoTen.setImmediate(false);
		txtHoTen.setWidth("481px");
		txtHoTen.setHeight("-1px");
		txtHoTen.setSecret(false);
		tabsheetCoBan.addComponent(txtHoTen);
		
		
				
		
		// txtGioiTinh
		txtGioiTinh = new OptionGroup("Gioi Tinh :", LIST_GENDER);
		txtGioiTinh.select(S_GENDER[0]) ;
		txtGioiTinh.setImmediate(false);
		txtGioiTinh.setWidth("-1px");
		txtGioiTinh.setHeight("-1px");
		tabsheetCoBan.addComponent(txtGioiTinh);
		
		// txtNgaySinh
		txtNgaySinh = new PopupDateField();
		txtNgaySinh.setImmediate(false);
		txtNgaySinh.setWidth("481px");
		txtNgaySinh.setHeight("-1px");
		txtNgaySinh.setInvalidAllowed(false);
		tabsheetCoBan.addComponent(txtNgaySinh);
		
		// txtDienThoai
		txtDienThoai = new TextField();
		txtDienThoai.setCaption("Dien Thoai :");
		txtDienThoai.setImmediate(false);
		txtDienThoai.setWidth("481px");
		txtDienThoai.setHeight("-1px");
		tabsheetCoBan.addComponent(txtDienThoai);
		
		// txtThongTinEmail
		txtThongTinEmail = new TextField();
		txtThongTinEmail.setCaption("Email :");
		txtThongTinEmail.setImmediate(false);
		txtThongTinEmail.setWidth("481px");
		txtThongTinEmail.setHeight("-1px");		
		tabsheetCoBan.addComponent(txtThongTinEmail);
		
		// txtDiaChi
		txtDiaChi = new TextArea();
		txtDiaChi.setCaption("Dia Chi :");
		txtDiaChi.setImmediate(false);
		txtDiaChi.setWidth("481px");
		txtDiaChi.setHeight("-1px");
		tabsheetCoBan.addComponent(txtDiaChi);
		
		// txtGhiChu
		txtGhiChu = new TextArea();
		txtGhiChu.setCaption("Ghi Chu :");
		txtGhiChu.setImmediate(false);
		txtGhiChu.setWidth("481px");
		txtGhiChu.setHeight("-1px");
		tabsheetCoBan.addComponent(txtGhiChu);
		
		// btnThongTInReset
		btnThongTInReset = new Button();
		btnThongTInReset.setCaption("Reset");
		btnThongTInReset.setImmediate(true);
		btnThongTInReset.setWidth("-1px");
		btnThongTInReset.setHeight("-1px");
		tabsheetCoBan.addComponent(btnThongTInReset);
		
		return tabsheetCoBan;
	}

	@AutoGenerated
	private VerticalLayout buildTabsheetCongTac() {
		// common part: create layout
		tabsheetCongTac = new VerticalLayout();
		tabsheetCongTac.setImmediate(false);
		tabsheetCongTac.setWidth("100.0%");
		tabsheetCongTac.setHeight("-1px");
		tabsheetCongTac.setMargin(true);
		tabsheetCongTac.setSpacing(true);
		
		// txtCongTacNgayBD
		txtCongTacNgayBD = new PopupDateField();
		txtCongTacNgayBD.setCaption("Thoi Diem Tham Gia Cong Tac :");
		txtCongTacNgayBD.setImmediate(false);
		txtCongTacNgayBD.setWidth("499px");
		txtCongTacNgayBD.setHeight("-1px");
		txtCongTacNgayBD.setInvalidAllowed(false);
		txtCongTacNgayBD.setRequired(true);
		tabsheetCongTac.addComponent(txtCongTacNgayBD);
		
		// txtHeSoLuong
		txtHeSoLuong = new TextField();
		txtHeSoLuong.setCaption("He So Luong :");
		txtHeSoLuong.setImmediate(false);
		txtHeSoLuong.setWidth("499px");
		txtHeSoLuong.setHeight("-1px");
		txtHeSoLuong.setRequired(true);		
		tabsheetCongTac.addComponent(txtHeSoLuong);
		
		// txtBacLuong
		txtBacLuong = new ComboBox("Bac Luong", LIST_BACLUONG);
		txtBacLuong.select(S_BACLUONG[0]) ;
//		txtBacLuong.setCaption("Bac Luong :");
		txtBacLuong.setImmediate(false);
		txtBacLuong.setWidth("499px");
		txtBacLuong.setHeight("-1px");
		tabsheetCongTac.addComponent(txtBacLuong);
		
		// verticalLayoutBoMon
		verticalLayoutBoMon = buildVerticalLayoutBoMon();
		tabsheetCongTac.addComponent(verticalLayoutBoMon);
		
		// btnCongTacReset
		btnCongTacReset = new Button();
		btnCongTacReset.setCaption("Reset");
		btnCongTacReset.setImmediate(true);
		btnCongTacReset.setWidth("-1px");
		btnCongTacReset.setHeight("-1px");
		tabsheetCongTac.addComponent(btnCongTacReset);
		
		
		
		//verticalShowInfo
		
		
		
		
		
		return tabsheetCongTac;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutBoMon() {
		// common part: create layout
		verticalLayoutBoMon = new VerticalLayout();
		verticalLayoutBoMon.setImmediate(false);
		verticalLayoutBoMon.setWidth("-1px");
		verticalLayoutBoMon.setHeight("-1px");
		verticalLayoutBoMon.setMargin(false);
		
		// txtBoMon
		txtBoMon = new ComboBox("Bo Mon Cong Tac :",GetDataFromDatabase.getBoMon());
		txtBoMon.setItemCaptionPropertyId("TenBM");
		txtBoMon.setItemCaptionMode(AbstractSelect.ITEM_CAPTION_MODE_PROPERTY);

		
		
		
		
//		txtBoMon.setCaption("Bo Mon Cong Tac :" );
		txtBoMon.setImmediate(false);
		txtBoMon.setWidth("499px");
		txtBoMon.setHeight("-1px");
		txtBoMon.setRequired(true);
//		txtBoMon.setContainerDataSource(GetDataFromDatabase.getBoMon()) ;
		verticalLayoutBoMon.addComponent(txtBoMon);
		
		// txtChucVu
		txtChucVu = new ComboBox("Chuc Vu :", LIST_CHUCVU);
		txtChucVu.select(S_CHUCVU[0]) ;
//		txtChucVu.setCaption("Chuc Vu :");
		txtChucVu.setImmediate(false);
		txtChucVu.setWidth("499px");
		txtChucVu.setHeight("-1px");
		txtChucVu.setRequired(true);
		verticalLayoutBoMon.addComponent(txtChucVu);
		
		// txtBoMonNgayBD
		txtBoMonNgayBD = new PopupDateField();
		txtBoMonNgayBD.setCaption("Ngay bat dau :");
		txtBoMonNgayBD.setImmediate(false);
		txtBoMonNgayBD.setWidth("499px");
		txtBoMonNgayBD.setHeight("-1px");
		txtBoMonNgayBD.setInvalidAllowed(false);
		txtBoMonNgayBD.setRequired(true);
		verticalLayoutBoMon.addComponent(txtBoMonNgayBD);
		
		// txtBoMonNgayKT
		txtBoMonNgayKT = new PopupDateField();
		txtBoMonNgayKT.setCaption("Ngay Ket thuc :");
		txtBoMonNgayKT.setImmediate(false);
		txtBoMonNgayKT.setWidth("499px");
		txtBoMonNgayKT.setHeight("-1px");
		txtBoMonNgayKT.setInvalidAllowed(false);
		verticalLayoutBoMon.addComponent(txtBoMonNgayKT);
		
		return verticalLayoutBoMon;
	}

	@AutoGenerated
	private VerticalLayout buildTabsheetHocHamHocVi() {
		// common part: create layout
		tabsheetHocHamHocVi = new VerticalLayout();
		tabsheetHocHamHocVi.setImmediate(false);
		tabsheetHocHamHocVi.setWidth("100.0%");
		tabsheetHocHamHocVi.setHeight("100.0%");
		tabsheetHocHamHocVi.setMargin(true);
		tabsheetHocHamHocVi.setSpacing(true);
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		tabsheetHocHamHocVi.addComponent(tabSheet_1);
		
		return tabsheetHocHamHocVi;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// verticalLayoutHocVi
		verticalLayoutHocVi = buildVerticalLayoutHocVi();
		tabSheet_1.addTab(verticalLayoutHocVi, "Hoc Vi", null);
		
		// verticalLayoutHocHam
		verticalLayoutHocHam = buildVerticalLayoutHocHam();
		tabSheet_1.addTab(verticalLayoutHocHam, "Hoc Ham", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutHocVi() {
		// common part: create layout
		verticalLayoutHocVi = new VerticalLayout();
		verticalLayoutHocVi.setImmediate(false);
		verticalLayoutHocVi.setWidth("100.0%");
		verticalLayoutHocVi.setHeight("-1px");
		verticalLayoutHocVi.setMargin(true);
		verticalLayoutHocVi.setSpacing(true);
		
		// txtHocViTen
		txtHocViTen = new ComboBox("Hoc Vi Dat Duoc :", LIST_HOCVI);
		txtHocViTen.select(S_HOCVI[0]) ;
//		txtHocViTen.setCaption("Hoc Vi Dat Duoc :");
		txtHocViTen.setImmediate(false);
		txtHocViTen.setWidth("462px");
		txtHocViTen.setHeight("-1px");
		txtHocViTen.setRequired(true);
		verticalLayoutHocVi.addComponent(txtHocViTen);
		
		// txtTenTruong
		txtTenTruong = new TextField();
		txtTenTruong.setCaption("Ten Truong da hoc :");
		txtTenTruong.setImmediate(false);
		txtTenTruong.setWidth("462px");
		txtTenTruong.setHeight("-1px");
		txtTenTruong.setRequired(true);
		txtTenTruong.setSecret(false);
		verticalLayoutHocVi.addComponent(txtTenTruong);
		
		// txtHocViNgayBD
		txtHocViNgayBD = new PopupDateField();
		txtHocViNgayBD.setCaption("Ngay Bat Dau :");
		txtHocViNgayBD.setImmediate(false);
		txtHocViNgayBD.setWidth("462px");
		txtHocViNgayBD.setHeight("-1px");
		txtHocViNgayBD.setInvalidAllowed(false);
		txtHocViNgayBD.setRequired(true);
		verticalLayoutHocVi.addComponent(txtHocViNgayBD);
		
		// txtHocViNgayKT
		txtHocViNgayKT = new PopupDateField();
		txtHocViNgayKT.setCaption("Ngay Ket Thuc :");
		txtHocViNgayKT.setImmediate(false);
		txtHocViNgayKT.setWidth("462px");
		txtHocViNgayKT.setHeight("-1px");
		txtHocViNgayKT.setInvalidAllowed(false);
		txtHocViNgayKT.setRequired(true);
		verticalLayoutHocVi.addComponent(txtHocViNgayKT);
		
		// txtHocViDiaChiTruong
		txtHocViDiaChiTruong = new TextArea();
		txtHocViDiaChiTruong.setCaption("Dia Chi Truong");
		txtHocViDiaChiTruong.setImmediate(false);
		txtHocViDiaChiTruong.setWidth("462px");
		txtHocViDiaChiTruong.setHeight("-1px");
		txtHocViDiaChiTruong.setRequired(true);
		verticalLayoutHocVi.addComponent(txtHocViDiaChiTruong);
		
		// btnHocViReset
		btnHocViReset = new Button();
		btnHocViReset.setCaption("Reset");
		btnHocViReset.setImmediate(true);
		btnHocViReset.setWidth("-1px");
		btnHocViReset.setHeight("-1px");
		verticalLayoutHocVi.addComponent(btnHocViReset);
		
		return verticalLayoutHocVi;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayoutHocHam() {
		// common part: create layout
		verticalLayoutHocHam = new VerticalLayout();
		verticalLayoutHocHam.setCaption("Hoc Ham");
		verticalLayoutHocHam.setImmediate(false);
		verticalLayoutHocHam.setWidth("100.0%");
		verticalLayoutHocHam.setHeight("-1px");
		verticalLayoutHocHam.setMargin(true);
		verticalLayoutHocHam.setSpacing(true);
		
		// txtTenHocHam
		txtTenHocHam = new ComboBox("Hoc Ham Dat Duoc :", LIST_HOCHAM);
		txtHocViTen.select(S_HOCHAM[0]) ;
		txtTenHocHam.setCaption("Hoc Ham Dat Duoc :");
		txtTenHocHam.setImmediate(false);
		txtTenHocHam.setWidth("462px");
		txtTenHocHam.setHeight("-1px");
		txtTenHocHam.setRequired(true);
		verticalLayoutHocHam.addComponent(txtTenHocHam);
		
		// txtHocHamNgayDatDuoc
		txtHocHamNgayDatDuoc = new PopupDateField();
		txtHocHamNgayDatDuoc.setCaption("Thoi Gian Duoc Phong Tang :");
		txtHocHamNgayDatDuoc.setImmediate(false);
		txtHocHamNgayDatDuoc.setWidth("462px");
		txtHocHamNgayDatDuoc.setHeight("-1px");
		txtHocHamNgayDatDuoc.setInvalidAllowed(false);
		txtHocHamNgayDatDuoc.setRequired(true);
		verticalLayoutHocHam.addComponent(txtHocHamNgayDatDuoc);
		
		// btnHocHamReset
		btnHocHamReset = new Button();
		btnHocHamReset.setCaption("Button");
		btnHocHamReset.setImmediate(false);
		btnHocHamReset.setWidth("-1px");
		btnHocHamReset.setHeight("-1px");
		verticalLayoutHocHam.addComponent(btnHocHamReset);
		
		return verticalLayoutHocHam;
	}

	@AutoGenerated
	private VerticalLayout buildTabsheetAccount() {
		// common part: create layout
		tabsheetAccount = new VerticalLayout();
		tabsheetAccount.setImmediate(false);
		tabsheetAccount.setWidth("100.0%");
		tabsheetAccount.setHeight("100.0%");
		tabsheetAccount.setMargin(true);
		tabsheetAccount.setSpacing(true);
		
		// txtUserName
		txtUserName = new TextField();
		txtUserName.setCaption("Tai khoan dang nhap :");
		txtUserName.setImmediate(false);
		txtUserName.setWidth("481px");
		txtUserName.setHeight("-1px");
		txtUserName.setRequired(true);
		txtUserName.setSecret(false);
		tabsheetAccount.addComponent(txtUserName);
		
		// txtPassword
		txtPassword = new PasswordField();
		txtPassword.setCaption("Mat khau dang nhap :");
		txtPassword.setImmediate(false);
		txtPassword.setWidth("481px");
		txtPassword.setHeight("-1px");
		txtPassword.setRequired(true);
		tabsheetAccount.addComponent(txtPassword);
		
		// btnDangNhapReset
		btnDangNhapReset = new Button();
		btnDangNhapReset.setCaption("Reset");
		btnDangNhapReset.setImmediate(true);
		btnDangNhapReset.setWidth("-1px");
		btnDangNhapReset.setHeight("-1px");
		tabsheetAccount.addComponent(btnDangNhapReset);
		
		return tabsheetAccount;
	}

	@AutoGenerated
	private VerticalLayout buildTabsheetNghienCuuKH() {
		// common part: create layout
		tabsheetNghienCuuKH = new VerticalLayout();
		tabsheetNghienCuuKH.setImmediate(false);
		tabsheetNghienCuuKH.setWidth("100.0%");
		tabsheetNghienCuuKH.setHeight("100.0%");
		tabsheetNghienCuuKH.setMargin(true);
		tabsheetNghienCuuKH.setSpacing(true);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		tabsheetNghienCuuKH.addComponent(horizontalLayout_1);
		
		// twinColSelect_1
		twinColSelect_1 = new TwinColSelect();
		twinColSelect_1.setContainerDataSource(GetDataFromDatabase.getDeTai()) ;
		twinColSelect_1.setItemCaptionPropertyId("TenCTNC");
		twinColSelect_1.setItemCaptionMode(AbstractSelect.ITEM_CAPTION_MODE_PROPERTY);

		twinColSelect_1.setCaption("Chon De Tai Dang Ky Thuc Hien :");
		twinColSelect_1.setImmediate(false);
		twinColSelect_1.setWidth("100.0%");
		twinColSelect_1.setHeight("-1px");
		twinColSelect_1.setRequired(true);
		tabsheetNghienCuuKH.addComponent(twinColSelect_1);
		tabsheetNghienCuuKH.setComponentAlignment(twinColSelect_1, new Alignment(40));
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Reset");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		tabsheetNghienCuuKH.addComponent(button_1);
		
		return tabsheetNghienCuuKH;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// txtNghienCuuNgayThamGia
		txtNghienCuuNgayThamGia = new PopupDateField();
		txtNghienCuuNgayThamGia.setCaption("Ngay Tham Gia :");
		txtNghienCuuNgayThamGia.setImmediate(false);
		txtNghienCuuNgayThamGia.setWidth("401px");
		txtNghienCuuNgayThamGia.setHeight("-1px");
		txtNghienCuuNgayThamGia.setInvalidAllowed(false);
		txtNghienCuuNgayThamGia.setRequired(true);
		horizontalLayout_1.addComponent(txtNghienCuuNgayThamGia);
		
		// txtNghienCuuNgayKT
		txtNghienCuuNgayKT = new PopupDateField();
		txtNghienCuuNgayKT.setCaption("Ngay Ket Thuc :");
		txtNghienCuuNgayKT.setImmediate(false);
		txtNghienCuuNgayKT.setWidth("390px");
		txtNghienCuuNgayKT.setHeight("-1px");
		txtNghienCuuNgayKT.setInvalidAllowed(false);
		horizontalLayout_1.addComponent(txtNghienCuuNgayKT);
		
		return horizontalLayout_1;
	}
	
	
	private VerticalLayout buildVerticalLayoutShowInfo() {
		// common part: create layout
		verticalShowInfo = new VerticalLayout();		
		verticalShowInfo.setVisible(false) ;
		verticalShowInfo.setImmediate(false);
		verticalShowInfo.setWidth("100.0%");
		verticalShowInfo.setHeight("100.0%");
		verticalShowInfo.setMargin(true);
		verticalShowInfo.setSpacing(true);
		
		Label title1 = new Label("<center><h1>Thong Tin Hoc Vi <h1></center>", Label.CONTENT_XHTML) ;
		tbHocVi = new Table() ;		
		tbHocVi.setWidth("100%") ;
		tbHocVi.setHeight("-1px") ;
		
//		tbHocVi.setPageLength(20) ;
		
		Label title2 = new Label("<center><h1>Thong Tin Hoc Ham <h1></center>", Label.CONTENT_XHTML) ;
		tbHocHam = new Table() ;		
		tbHocHam.setWidth("100%") ;
		tbHocHam.setHeight("-1px") ;
//		tbNghienCuu.setPageLength(20) ;
		
		Label title3 = new Label("<center><h1>Cac de tai nghien cuu da tham gia <h1></center>", Label.CONTENT_XHTML) ;
		tbNghienCuu = new Table() ;		
		tbNghienCuu.setWidth("100%") ;
		tbNghienCuu.setHeight("-1px") ;
//		tbHocVi.setPageLength(20) ;
		
		verticalShowInfo.addComponent(title1);
		verticalShowInfo.addComponent(tbHocVi);
		verticalShowInfo.addComponent(title2);
		verticalShowInfo.addComponent(tbHocHam);
		verticalShowInfo.addComponent(title3);
		verticalShowInfo.addComponent(tbNghienCuu);
		
		return verticalShowInfo;
	}
	
	
	
	
	

}
