package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.constants.Constants;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class rightContentSample extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table;
	@AutoGenerated
	private Label lblTitle;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentSample() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		lblTitle.setContentMode(3) ;
		lblTitle.setDescription("<h1>Danh Sach Giang Vien</h1>");
		lblTitle.setValue("");

		contentTable() ;
	}

	private void contentTable()
	{
		table.addContainerProperty("STT", Integer.class, null) ;
		table.addContainerProperty("Ma so", String.class, null) ;
		table.addContainerProperty("Ho ", String.class, null);
		table.addContainerProperty("Ten", String.class, null);
		table.addContainerProperty("Bo mon", String.class, null);
		table.addContainerProperty("Hoc ham,hoc vi", String.class, null);
		table.addContainerProperty("Chuc vu",String.class, null);
		
		for (int i=0; i< 15; i++)
			table.addItem(new Object[]{new Integer(i+1),"0001", "Nguyen Van ", "A","Khoa hoc may tinh", "Tien si", "Giang vien chinh" }, new Integer(i));
	
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
//		mainLayout.setWidth(Constants.RIGHT_MENU, Sizeable.UNITS_PIXELS);
//		mainLayout.setWidth("60%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
	
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setCaption("this is the content ");
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("Label");
		mainLayout.addComponent(lblTitle);
		mainLayout.setComponentAlignment(lblTitle, new Alignment(20));
		
		// table
		table = new Table();
		table.setImmediate(false);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		mainLayout.addComponent(table);
		mainLayout.setComponentAlignment(table, new Alignment(20));
		
		return mainLayout;
	}
	
	

}
