package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.detailedInfo.*;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;

public class rightContentRegistedResearching extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btnApply;
	@AutoGenerated
	private TextArea txtContent;
	@AutoGenerated
	private Table tableListWhoWith;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btnAdd;
	@AutoGenerated
	private ComboBox comboBoxList;
	@AutoGenerated
	private ComboBox comboBoxStatus;
	@AutoGenerated
	private PopupDateField popupDateEndedDay;
	@AutoGenerated
	private PopupDateField popupDateStartedDay;
	@AutoGenerated
	private TextArea txtName;
	@AutoGenerated
	private Label lblTitle;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentRegistedResearching() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		
		for (int i=0; i<10 ; i++) comboBoxStatus.addItem(new String("test"+i)) ;
		
//		tableListWhoWith.setColumnHeader("stt", "stt11") ;
//		tableListWhoWith.setColumnHeader("stt", "stt11") ;
//		tableListWhoWith.setColumnHeader("stt", "stt11") ;
//		tableListWhoWith.
//		tableListWhoWith.addContainerProperty("STT", Integer.class, null) ;
//		tableListWhoWith.addContainerProperty("ID", String.class, null) ;
//		tableListWhoWith.addContainerProperty("ho va ten", Integer.class, null) ;
//		tableListWhoWith.addContainerProperty("Bo mon", Integer.class, null) ;
//		tableListWhoWith.addContainerProperty("tien si", Integer.class, null) ;
		tableListWhoWith.setColumnFooter("total", "total"+ tableListWhoWith.size()) ;
		tableListWhoWith.setColumnFooter("value", "value") ;
		tableListWhoWith.setFooterVisible(true) ;
	
		final BeanItemContainer<TeacherBean> beans = new BeanItemContainer<TeacherBean>(TeacherBean.class);

		tableListWhoWith.setContainerDataSource(beans) ;
		
//		Table.
		
		
		btnAdd.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
				beans.addBean(new TeacherBean()) ;
				
			}
		});
		


	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("632px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("632px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue("<center><h1>Dang ky de tai nghien cuu</h1></center>");
		lblTitle.setContentMode(3);
		mainLayout.addComponent(lblTitle);
		
		// txtName
		txtName = new TextArea();
		txtName.setCaption("Ten de tai");
		txtName.setImmediate(false);
		txtName.setWidth("100.0%");
		txtName.setHeight("65px");
		mainLayout.addComponent(txtName);
		
		// popupDateStartedDay
		popupDateStartedDay = new PopupDateField();
		popupDateStartedDay.setCaption("Started day :");
		popupDateStartedDay.setImmediate(false);
		popupDateStartedDay.setWidth("300px");
		popupDateStartedDay.setHeight("-1px");
		popupDateStartedDay.setInvalidAllowed(false);
		mainLayout.addComponent(popupDateStartedDay);
		
		// popupDateEndedDay
		popupDateEndedDay = new PopupDateField();
		popupDateEndedDay.setCaption("Ended day :");
		popupDateEndedDay.setImmediate(false);
		popupDateEndedDay.setWidth("300px");
		popupDateEndedDay.setHeight("-1px");
		popupDateEndedDay.setInvalidAllowed(false);
		mainLayout.addComponent(popupDateEndedDay);
		
		// comboBoxStatus
		comboBoxStatus = new ComboBox();
		comboBoxStatus.setCaption("Status :");
		comboBoxStatus.setImmediate(false);
		comboBoxStatus.setWidth("300px");
		comboBoxStatus.setHeight("-1px");
		mainLayout.addComponent(comboBoxStatus);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// tableListWhoWith
		tableListWhoWith = new Table();
		tableListWhoWith.setCaption("Danh sach");
		tableListWhoWith.setImmediate(false);
		tableListWhoWith.setWidth("100.0%");
		tableListWhoWith.setHeight("114px");
		mainLayout.addComponent(tableListWhoWith);
		
		// txtContent
		txtContent = new TextArea();
		txtContent.setCaption("Noi dung thuc hien");
		txtContent.setImmediate(false);
		txtContent.setWidth("100.0%");
		txtContent.setHeight("-1px");
		mainLayout.addComponent(txtContent);
		
		// btnApply
		btnApply = new Button();
		btnApply.setCaption("Apply");
		btnApply.setImmediate(true);
		btnApply.setWidth("100px");
		btnApply.setHeight("-1px");
		mainLayout.addComponent(btnApply);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// comboBoxList
		comboBoxList = new ComboBox();
		comboBoxList.setCaption("Who with :");
		comboBoxList.setImmediate(false);
		comboBoxList.setWidth("100.0%");
		comboBoxList.setHeight("-1px");
		horizontalLayout_1.addComponent(comboBoxList);
		horizontalLayout_1.setExpandRatio(comboBoxList, 1.0f);
		
		// btnAdd
		btnAdd = new Button();
		btnAdd.setCaption("Add");
		btnAdd.setImmediate(true);
		btnAdd.setWidth("-1px");
		btnAdd.setHeight("-1px");
		horizontalLayout_1.addComponent(btnAdd);
		horizontalLayout_1.setComponentAlignment(btnAdd, new Alignment(10));
		
		return horizontalLayout_1;
	}

}
