package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class rightContentAddTeacher extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button btSubmit;
	@AutoGenerated
	private ComboBox cbMaKTKL;
	@AutoGenerated
	private ComboBox cbMaCTNC;
	@AutoGenerated
	private ComboBox cbLoaigiangvien;
	@AutoGenerated
	private ComboBox cbNamcongtac;
	@AutoGenerated
	private ComboBox cbBomon;
	@AutoGenerated
	private ComboBox cbChucvu;
	@AutoGenerated
	private TextField txtDienthoai;
	@AutoGenerated
	private TextArea txtADiachi;
	@AutoGenerated
	private ComboBox cbGioitinh;
	@AutoGenerated
	private PopupDateField pdNgaysinh;
	@AutoGenerated
	private TextField txtHoTen;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentAddTeacher() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<H1>Thêm thông tin giảng viên</H1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// txtHoTen
		txtHoTen = new TextField();
		txtHoTen.setCaption("Họ tên giảng viên:");
		txtHoTen.setImmediate(false);
		txtHoTen.setWidth("-1px");
		txtHoTen.setHeight("20px");
		txtHoTen.setSecret(false);
		mainLayout.addComponent(txtHoTen);
		
		// pdNgaysinh
		pdNgaysinh = new PopupDateField();
		pdNgaysinh.setCaption("Ngày sinh");
		pdNgaysinh.setImmediate(false);
		pdNgaysinh.setWidth("-1px");
		pdNgaysinh.setHeight("-1px");
		pdNgaysinh.setInvalidAllowed(false);
		mainLayout.addComponent(pdNgaysinh);
		
		// cbGioitinh
		cbGioitinh = new ComboBox();
		cbGioitinh.setCaption("Giới Tính");
		cbGioitinh.setImmediate(false);
		cbGioitinh.setWidth("-1px");
		cbGioitinh.setHeight("-1px");
		mainLayout.addComponent(cbGioitinh);
		
		// txtADiachi
		txtADiachi = new TextArea();
		txtADiachi.setCaption("Địa chỉ");
		txtADiachi.setImmediate(false);
		txtADiachi.setWidth("-1px");
		txtADiachi.setHeight("-1px");
		mainLayout.addComponent(txtADiachi);
		
		// txtDienthoai
		txtDienthoai = new TextField();
		txtDienthoai.setCaption("Điện thoại");
		txtDienthoai.setImmediate(false);
		txtDienthoai.setWidth("-1px");
		txtDienthoai.setHeight("-1px");
		txtDienthoai.setSecret(false);
		mainLayout.addComponent(txtDienthoai);
		
		// cbChucvu
		cbChucvu = new ComboBox();
		cbChucvu.setCaption("chức vụ");
		cbChucvu.setImmediate(false);
		cbChucvu.setWidth("-1px");
		cbChucvu.setHeight("-1px");
		mainLayout.addComponent(cbChucvu);
		
		// cbBomon
		cbBomon = new ComboBox();
		cbBomon.setCaption("Bộ môn");
		cbBomon.setImmediate(false);
		cbBomon.setWidth("-1px");
		cbBomon.setHeight("-1px");
		mainLayout.addComponent(cbBomon);
		
		// cbNamcongtac
		cbNamcongtac = new ComboBox();
		cbNamcongtac.setCaption("Năm công tác");
		cbNamcongtac.setImmediate(false);
		cbNamcongtac.setWidth("-1px");
		cbNamcongtac.setHeight("-1px");
		mainLayout.addComponent(cbNamcongtac);
		
		// cbLoaigiangvien
		cbLoaigiangvien = new ComboBox();
		cbLoaigiangvien.setCaption("Loại giảng viên");
		cbLoaigiangvien.setImmediate(false);
		cbLoaigiangvien.setWidth("-1px");
		cbLoaigiangvien.setHeight("-1px");
		mainLayout.addComponent(cbLoaigiangvien);
		
		// cbMaCTNC
		cbMaCTNC = new ComboBox();
		cbMaCTNC.setCaption("Mã công trình nghiên cứu");
		cbMaCTNC.setImmediate(false);
		cbMaCTNC.setWidth("-1px");
		cbMaCTNC.setHeight("-1px");
		mainLayout.addComponent(cbMaCTNC);
		
		// cbMaKTKL
		cbMaKTKL = new ComboBox();
		cbMaKTKL.setCaption("Mã khen thuởng kỹ luật");
		cbMaKTKL.setImmediate(false);
		cbMaKTKL.setWidth("-1px");
		cbMaKTKL.setHeight("-1px");
		mainLayout.addComponent(cbMaKTKL);
		
		// btSubmit
		btSubmit = new Button();
		btSubmit.setCaption("Submit");
		btSubmit.setImmediate(false);
		btSubmit.setWidth("-1px");
		btSubmit.setHeight("-1px");
		mainLayout.addComponent(btSubmit);
		
		return mainLayout;
	}

}
