package cit.group10.qlGiangvien.widgets;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class rightContentAddNewSubject extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button btThem;
	@AutoGenerated
	private Button btNhaplai;
	@AutoGenerated
	private TextArea txtNgiencuuphattrien;
	@AutoGenerated
	private TextArea txtGiangday;
	@AutoGenerated
	private TextArea txtNhansu;
	@AutoGenerated
	private TextArea txtLichsu;
	@AutoGenerated
	private TextField txtTenMB;
	@AutoGenerated
	private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public rightContentAddNewSubject() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("621px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("621px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("<h1> Thông tin bộ môn</h1>");
		label_1.setContentMode(3);
		mainLayout.addComponent(label_1);
		
		// txtTenMB
		txtTenMB = new TextField();
		txtTenMB.setCaption("Tên bộ môn");
		txtTenMB.setImmediate(false);
		txtTenMB.setWidth("380px");
		txtTenMB.setHeight("24px");
		txtTenMB.setSecret(false);
		mainLayout.addComponent(txtTenMB);
		
		// txtLichsu
		txtLichsu = new TextArea();
		txtLichsu.setCaption("Lích sử phát triển");
		txtLichsu.setImmediate(false);
		txtLichsu.setWidth("520px");
		txtLichsu.setHeight("-1px");
		mainLayout.addComponent(txtLichsu);
		
		// txtNhansu
		txtNhansu = new TextArea();
		txtNhansu.setCaption("Nhân sự trong môn môn");
		txtNhansu.setImmediate(false);
		txtNhansu.setWidth("520px");
		txtNhansu.setHeight("-1px");
		mainLayout.addComponent(txtNhansu);
		
		// txtGiangday
		txtGiangday = new TextArea();
		txtGiangday.setCaption("Giảng dạy");
		txtGiangday.setImmediate(false);
		txtGiangday.setWidth("520px");
		txtGiangday.setHeight("-1px");
		mainLayout.addComponent(txtGiangday);
		
		// txtNgiencuuphattrien
		txtNgiencuuphattrien = new TextArea();
		txtNgiencuuphattrien.setCaption("Nghiên cứu phát triển");
		txtNgiencuuphattrien.setImmediate(false);
		txtNgiencuuphattrien.setWidth("520px");
		txtNgiencuuphattrien.setHeight("-1px");
		mainLayout.addComponent(txtNgiencuuphattrien);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("481px");
		horizontalLayout_1.setHeight("43px");
		horizontalLayout_1.setMargin(false);
		
		// btNhaplai
		btNhaplai = new Button();
		btNhaplai.setCaption("nhập lại");
		btNhaplai.setImmediate(false);
		btNhaplai.setWidth("-1px");
		btNhaplai.setHeight("-1px");
		horizontalLayout_1.addComponent(btNhaplai);
		
		// btThem
		btThem = new Button();
		btThem.setCaption("Thêm");
		btThem.setImmediate(false);
		btThem.setWidth("-1px");
		btThem.setHeight("-1px");
		horizontalLayout_1.addComponent(btThem);
		
		return horizontalLayout_1;
	}

}
