package cit.group10.qlGiangvien.widgets;

import cit.group10.qlGiangvien.QlgiangvienApplication;
import cit.group10.qlGiangvien.constants.Constants;

import com.vaadin.terminal.ExternalResource;
import com.vaadin.terminal.Sizeable;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.themes.BaseTheme;

public class topLogin extends CustomComponent implements Constants{


	private HorizontalLayout mainLayout;
	private Button lblLogout;
	private Button lblSetting;
//	private Button btn;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public topLogin() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		mainLayout.setWidth(Constants.WIDTH_MAX, Sizeable.UNITS_PIXELS) ;
	}

	
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("40px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		

		// lblSetting
		lblSetting = new Button(Constants.SETTING);
		lblSetting.setImmediate(false);
		lblSetting.setWidth("-1px");
		lblSetting.setHeight("-1px");
		lblSetting.setStyleName(BaseTheme.BUTTON_LINK) ;
		lblSetting.setIcon(new ThemeResource("img/setting.png"));		

		
		mainLayout.addComponent(lblSetting);
		mainLayout.setExpandRatio(lblSetting, 0.5f);
		mainLayout.setComponentAlignment(lblSetting, new Alignment(34));
		
		
		// lblLogout
		lblLogout = new Button(Constants.LOGOUT);
		lblLogout.setImmediate(false);
		lblLogout.setWidth("-1px");
		lblLogout.setHeight("-1px");
		lblLogout.setStyleName(BaseTheme.BUTTON_LINK) ;
		lblLogout.setIcon(new ThemeResource("img/logout.png"));
		lblLogout.addListener(Button.ClickEvent.class, this, "logout") ;
		
		
		mainLayout.addComponent(lblLogout);
		mainLayout.setComponentAlignment(lblLogout, new Alignment(34));

		return mainLayout;
	}
	
	
	
	public void logout(){
		getWindow().showNotification("in logout function") ;
		this.getApplication().close() ;

	}
	public void setting(){
		getWindow().showNotification("setting function") ;
	}
	
}
